//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc /T ps_5_0 /O1 /E PS_BLOOMTEXTURE /Fo
//    \\?\C:\Users\Jonas\VektoriaV13_Beta\dauwilliwasmacha\VektoriaApp\Shaders\Cache\Object\Release\PS_BLOOMTEXTURE.obj
//    /Fe
//    \\?\C:\Users\Jonas\VektoriaV13_Beta\dauwilliwasmacha\VektoriaApp\Shaders\Cache\Error\PS_BLOOMTEXTURE.txt
//    /Fc
//    \\?\C:\Users\Jonas\VektoriaV13_Beta\dauwilliwasmacha\VektoriaApp\Shaders\Cache\Assembly\95c16455.asm
//    \\?\C:\Users\Jonas\VektoriaV13_Beta\dauwilliwasmacha\VektoriaApp\shaders\source\BloomPost.hlsl
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// linearSampler                     sampler      NA          NA    1        1
// tex2D[7]                          texture  float4          2d   22        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_POSITION              0   xyzw        0      POS  float       
// TEXCOORD                 0   xy          1     NONE  float   xy  
// TEXCOORD                 2   xyzw        2     NONE  float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_TARGET                0   xyzw        0   TARGET  float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_sampler s1, mode_default
dcl_resource_texture2d (float,float,float,float) t22
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 1
sample_indexable(texture2d)(float,float,float,float) r0.xyzw, v1.xyxx, t22.xyzw, s1
add r0.xyzw, r0.xyzw, l(-0.600000, -0.600000, -0.600000, -0.600000)
mul_sat o0.xyzw, r0.xyzw, l(2.500000, 2.500000, 2.500000, 2.500000)
ret 
// Approximately 4 instruction slots used
