//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc /T vs_5_0 /O1 /E RSMVS /Fo
//    \\?\C:\Users\Jonas\VektoriaV13_Beta\dauwilliwasmacha\VektoriaApp\Shaders\Cache\Object\Release\RSMVS.obj
//    /Fe
//    \\?\C:\Users\Jonas\VektoriaV13_Beta\dauwilliwasmacha\VektoriaApp\Shaders\Cache\Error\RSMVS.txt
//    /Fc
//    \\?\C:\Users\Jonas\VektoriaV13_Beta\dauwilliwasmacha\VektoriaApp\Shaders\Cache\Assembly\c1de8a4.asm
//    \\?\C:\Users\Jonas\VektoriaV13_Beta\dauwilliwasmacha\VektoriaApp\shaders\source\reflectiveshadowmaps.hlsl
//
//
// Buffer Definitions: 
//
// cbuffer cbPerObject
// {
//
//   float4x4 g_mWorld;                 // Offset:    0 Size:    64
//
// }
//
// cbuffer cbPerCamera
// {
//
//   float4x4 g_mViewProj;              // Offset:    0 Size:    64
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// cbPerObject                       cbuffer      NA          NA    0        1
// cbPerCamera                       cbuffer      NA          NA    1        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// POSITION                 0   xyzw        0     NONE  float   xyzw
// NORMAL                   0   xyz         1     NONE  float   xyz 
// TEXCOORD                 0   xy          2     NONE  float   xy  
// TANGENT                  0   xyz         3     NONE  float       
// BITANGENT                0   xyz         4     NONE  float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// NORMAL                   0   xyz         0     NONE  float   xyz 
// TEXCOORD                 0   xy          1     NONE  float   xy  
// TEXCOORD                 1   xyz         2     NONE  float   xyz 
// SV_POSITION              0   xyzw        3      POS  float   xyzw
//
vs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb0[4], immediateIndexed
dcl_constantbuffer cb1[4], immediateIndexed
dcl_input v0.xyzw
dcl_input v1.xyz
dcl_input v2.xy
dcl_output o0.xyz
dcl_output o1.xy
dcl_output o2.xyz
dcl_output_siv o3.xyzw, position
dcl_temps 1
dp3 o0.x, v1.xyzx, cb0[0].xyzx
dp3 o0.y, v1.xyzx, cb0[1].xyzx
dp3 o0.z, v1.xyzx, cb0[2].xyzx
mov o1.xy, v2.xyxx
dp4 r0.x, v0.xyzw, cb0[0].xyzw
dp4 r0.y, v0.xyzw, cb0[1].xyzw
dp4 r0.z, v0.xyzw, cb0[2].xyzw
mov o2.xyz, r0.xyzx
dp4 r0.w, v0.xyzw, cb0[3].xyzw
dp4 o3.x, r0.xyzw, cb1[0].xyzw
dp4 o3.y, r0.xyzw, cb1[1].xyzw
dp4 o3.z, r0.xyzw, cb1[2].xyzw
dp4 o3.w, r0.xyzw, cb1[3].xyzw
ret 
// Approximately 14 instruction slots used
