//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer cbPerFrame
// {
//
//   float4x4 g_mView;                  // Offset:    0 Size:    64 [unused]
//   float4x4 g_mViewInv;               // Offset:   64 Size:    64 [unused]
//   float4x4 g_mProjection;            // Offset:  128 Size:    64 [unused]
//   float4x4 g_mProjectionInv;         // Offset:  192 Size:    64
//   float4x4 g_mProjectionInvViewport; // Offset:  256 Size:    64 [unused]
//   float4 g_f4AmbientColorUp;         // Offset:  320 Size:    16
//   float4 g_f4AmbientColorDown;       // Offset:  336 Size:    16
//   float3 g_f3CameraPos;              // Offset:  352 Size:    12
//   float g_fAlphaTest;                // Offset:  364 Size:     4 [unused]
//   uint g_uNumLights;                 // Offset:  368 Size:     4 [unused]
//   uint g_uNumSpotLights;             // Offset:  372 Size:     4 [unused]
//   uint g_uWindowWidth;               // Offset:  376 Size:     4 [unused]
//   uint g_uWindowHeight;              // Offset:  380 Size:     4 [unused]
//   uint g_uMaxNumLightsPerTile;       // Offset:  384 Size:     4
//   uint g_uMaxNumElementsPerTile;     // Offset:  388 Size:     4
//   uint g_uNumTilesX;                 // Offset:  392 Size:     4
//   uint g_uNumTilesY;                 // Offset:  396 Size:     4 [unused]
//   uint g_uMaxVPLs;                   // Offset:  400 Size:     4 [unused]
//   uint g_uMaxNumVPLsPerTile;         // Offset:  404 Size:     4 [unused]
//   uint g_uMaxNumVPLElementsPerTile;  // Offset:  408 Size:     4 [unused]
//   float g_fVPLSpotStrength;          // Offset:  412 Size:     4 [unused]
//   float g_fVPLSpotRadius;            // Offset:  416 Size:     4 [unused]
//   float g_fVPLPointStrength;         // Offset:  420 Size:     4 [unused]
//   float g_fVPLPointRadius;           // Offset:  424 Size:     4 [unused]
//   float g_fVPLRemoveBackFaceContrib; // Offset:  428 Size:     4 [unused]
//   float g_fVPLColorThreshold;        // Offset:  432 Size:     4 [unused]
//   float g_fVPLBrightnessThreshold;   // Offset:  436 Size:     4 [unused]
//   float g_fPerFramePad1;             // Offset:  440 Size:     4 [unused]
//   float g_fPerFramePad2;             // Offset:  444 Size:     4 [unused]
//
// }
//
// cbuffer cbShadowConstants
// {
//
//   float4x4 g_mPointShadowViewProj[72];// Offset:    0 Size:  4608
//   float4x4 g_mSpotShadowViewProj[12];// Offset: 4608 Size:   768
//   float4 g_f4ShadowBias;             // Offset: 5376 Size:    16
//
// }
//
// cbuffer TexInfo
// {
//
//   float4 f4ColorAmbient;             // Offset:    0 Size:    16 [unused]
//   float fA;                          // Offset:   16 Size:     4 [unused]
//   float fH;                          // Offset:   20 Size:     4
//   float fBumpStrength;               // Offset:   24 Size:     4
//   float frTransparency;              // Offset:   28 Size:     4
//   float4 f4ColorSSS;                 // Offset:   32 Size:    16
//   float4 f4SSSBRDFParams;            // Offset:   48 Size:    16
//   uint uImage;                       // Offset:   64 Size:     4 [unused]
//   uint uGlow;                        // Offset:   68 Size:     4 [unused]
//   uint uSpecular;                    // Offset:   72 Size:     4
//   uint uBump;                        // Offset:   76 Size:     4
//   uint uImageBlack;                  // Offset:   80 Size:     4 [unused]
//   uint uGlowAsImage;                 // Offset:   84 Size:     4 [unused]
//   uint uSpecularAsImage;             // Offset:   88 Size:     4 [unused]
//   uint uHeightAsImage;               // Offset:   92 Size:     4 [unused]
//   uint uImageWhite;                  // Offset:   96 Size:     4 [unused]
//   uint uGlowWhite;                   // Offset:  100 Size:     4 [unused]
//   uint uSpecularWhite;               // Offset:  104 Size:     4
//   uint uHeight;                      // Offset:  108 Size:     4 [unused]
//   uint uShadingOn;                   // Offset:  112 Size:     4 [unused]
//   uint uGlowAsAmbient;               // Offset:  116 Size:     4 [unused]
//   uint uChromaKeying;                // Offset:  120 Size:     4
//   uint uEnvironment;                 // Offset:  124 Size:     4
//   uint uPOM;                         // Offset:  128 Size:     4 [unused]
//   uint uTexBRDF;                     // Offset:  132 Size:     4 [unused]
//   uint uTexSSS;                      // Offset:  136 Size:     4
//   uint uReflectionMap;               // Offset:  140 Size:     4
//   uint uixPos;                       // Offset:  144 Size:     4
//   uint uiyPos;                       // Offset:  148 Size:     4
//   uint uixPics;                      // Offset:  152 Size:     4
//   uint uiyPics;                      // Offset:  156 Size:     4
//   float fSpecularRoughness;          // Offset:  160 Size:     4
//   float fSpecularIOR;                // Offset:  164 Size:     4
//   uint uPad1;                        // Offset:  168 Size:     4 [unused]
//   uint uPad2;                        // Offset:  172 Size:     4 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// g_Sampler                         sampler      NA          NA    0        1
// g_ShadowSampler                 sampler_c      NA          NA    1        1
// g_pointLightCenterAndRadiusBuffer    texture  float4         buf    2        1
// g_pointLightColorBuffer           texture  float4         buf    3        1
// g_perTilePointLightIndexBuffer    texture    uint         buf    4        1
// g_spotLightCenterAndRadiusBuffer    texture  float4         buf    5        1
// g_spotLightColorBuffer            texture  float4         buf    6        1
// g_spotLightParamsBuffer           texture  float4         buf    7        1
// g_perTileSpotLightIndexBuffer     texture    uint         buf    8        1
// g_PointShadowAtlas                texture  float4          2d   13        1
// g_SpotShadowAtlas                 texture  float4          2d   14        1
// tex2D[0]                          texture  float4          2d   15        1
// tex2D[3]                          texture  float4          2d   18        1
// tex2D[4]                          texture  float4          2d   19        1
// tex2D[6]                          texture  float4          2d   21        1
// cbPerFrame                        cbuffer      NA          NA    2        1
// cbShadowConstants                 cbuffer      NA          NA    3        1
// TexInfo                           cbuffer      NA          NA    5        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_POSITION              0   xyzw        0      POS  float   xyz 
// NORMAL                   0   xyz         1     NONE  float   xyz 
// TEXCOORD                 0   xyz         2     NONE  float   xyz 
// TEXCOORD                 1   xy          3     NONE  float   xy  
// TANGENT                  0   xyz         4     NONE  float       
// BITANGENT                0   xyz         5     NONE  float       
// TEXCOORD                 2   xyz         6     NONE  float   xyz 
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_TARGET                0   xyzw        0   TARGET  float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb2[25], immediateIndexed
dcl_constantbuffer cb3[337], dynamicIndexed
dcl_constantbuffer cb5[11], immediateIndexed
dcl_sampler s0, mode_default
dcl_sampler s1, mode_comparison
dcl_resource_buffer (float,float,float,float) t2
dcl_resource_buffer (float,float,float,float) t3
dcl_resource_buffer (uint,uint,uint,uint) t4
dcl_resource_buffer (float,float,float,float) t5
dcl_resource_buffer (float,float,float,float) t6
dcl_resource_buffer (float,float,float,float) t7
dcl_resource_buffer (uint,uint,uint,uint) t8
dcl_resource_texture2d (float,float,float,float) t13
dcl_resource_texture2d (float,float,float,float) t14
dcl_resource_texture2d (float,float,float,float) t15
dcl_resource_texture2d (float,float,float,float) t18
dcl_resource_texture2d (float,float,float,float) t19
dcl_resource_texture2d (float,float,float,float) t21
dcl_input_ps_siv linear noperspective v0.xyz, position
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xy
dcl_input_ps linear v6.xyz
dcl_output o0.xyzw
dcl_temps 27
ult r0.xy, l(1, 1, 0, 0), cb5[9].ywyy
or r0.x, r0.y, r0.x
utof r1.xyzw, cb5[9].xyzw
div r0.yz, r1.xxyx, r1.zzwz
div r1.xy, l(1.000000, 1.000000, 1.000000, 1.000000), r1.zwzz
mad r0.yz, v3.xxyx, r1.xxyx, r0.yyzy
movc r0.xy, r0.xxxx, r0.yzyy, v3.xyxx
sample_indexable(texture2d)(float,float,float,float) r1.xyz, r0.xyxx, t18.xyzw, s0
mad r2.xyz, r1.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
dp3 r0.z, v1.xyzx, v1.xyzx
rsq r0.z, r0.z
mul r3.xyz, r0.zzzz, v1.xyzx
if_nz cb5[4].z
  sample_indexable(texture2d)(float,float,float,float) r4.xyz, r0.xyxx, t15.xyzw, s0
else 
  mov r4.xyz, l(0,0,0,0)
endif 
mul r5.xyz, r3.yzxy, l(0.000000, 0.000000, 1.000000, 0.000000)
mad r6.xyz, r3.yzxy, l(1.000000, 0.000000, 0.000000, 0.000000), -r5.yzxy
mad r5.xyz, -r3.zxyz, l(1.000000, 0.000000, 0.000000, 0.000000), r5.xyzx
dp2 r0.z, r6.xyxx, r6.xyxx
dp2 r0.w, r5.xzxx, r5.xzxx
sqrt r0.zw, r0.zzzw
lt r0.z, r0.w, r0.z
if_nz r0.z
  mov r5.xyz, r6.xyzx
endif 
mul r6.xyz, r3.zxyz, r5.yzxy
mad r6.xyz, r3.yzxy, r5.zxyz, -r6.xyzx
dp3 r0.z, -r6.xyzx, -r6.xyzx
rsq r0.z, r0.z
mul r6.xyz, r0.zzzz, -r6.xyzx
if_nz cb5[4].w
  mad r0.zw, r1.xxxy, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -1.000000)
  mul r0.zw, r0.zzzw, cb5[1].zzzz
  mul r1.xyz, r6.xyzx, r0.wwww
  mad r1.xyz, r0.zzzz, r5.xyzx, r1.xyzx
  add r1.xyz, r1.xyzx, v1.xyzx
  dp3 r0.z, r1.xyzx, r1.xyzx
  rsq r0.z, r0.z
  mul r1.xyz, r0.zzzz, r1.xyzx
else 
  mov r1.xyz, v1.xyzx
endif 
mul r5.xyz, r2.yyyy, r5.xyzx
mad r2.xyw, r2.xxxx, r6.xyxz, r5.xyxz
mad r2.xyz, r2.zzzz, r3.xyzx, r2.xywx
dp3 r0.z, r2.xyzx, r2.xyzx
rsq r0.z, r0.z
mul r2.xyz, r0.zzzz, r2.xyzx
add r3.xyz, -v2.xyzx, cb2[22].xyzx
dp3 r0.z, r3.xyzx, r3.xyzx
rsq r0.z, r0.z
mul r5.xyz, r0.zzzz, r3.xyzx
mul r6.xy, v0.xyxx, l(0.031250, 0.031250, 0.000000, 0.000000)
round_ni r6.xy, r6.xyxx
utof r0.w, cb2[24].z
mad r0.w, r6.y, r0.w, r6.x
ftou r0.w, r0.w
imul null, r1.w, cb2[24].y, r0.w
ld_indexable(buffer)(uint,uint,uint,uint) r2.w, r1.wwww, t4.yzwx
imad r6.xyzw, cb2[24].yyyy, r0.wwww, l(1, 4, 2, 3)
ld_indexable(buffer)(uint,uint,uint,uint) r0.w, r6.xxxx, t4.yzwx
ishl r2.w, r2.w, l(16)
or r0.w, r0.w, r2.w
mad r2.w, v0.z, cb2[15].z, cb2[15].w
div r2.w, l(1.000000, 1.000000, 1.000000, 1.000000), r2.w
lt r0.w, r2.w, r0.w
iadd r3.w, r6.y, cb2[24].x
movc r4.w, r0.w, r6.y, r3.w
ld_indexable(buffer)(uint,uint,uint,uint) r5.w, r6.zzzz, t4.yzwx
ld_indexable(buffer)(uint,uint,uint,uint) r7.x, r6.wwww, t4.xyzw
movc r0.w, r0.w, r5.w, r7.x
iadd r0.w, r4.w, r0.w
mul r5.w, cb5[10].x, cb5[10].x
dp3_sat r5.x, r2.xyzx, r5.xyzx
mul r5.y, r5.w, r5.w
mad r5.z, r5.w, r5.w, l(-1.000000)
add r7.x, l(1.000000), -cb5[10].y
mul r7.y, r5.w, l(0.500000)
mad r5.w, -r5.w, l(0.500000), l(1.000000)
mad r5.x, r5.x, r5.w, r7.y
div r5.x, l(1.000000, 1.000000, 1.000000, 1.000000), r5.x
add r7.z, l(1.000000), -cb5[1].w
add r4.xyz, r4.xyzx, r4.xyzx
mul r7.z, r7.z, l(8.000000)
sample_indexable(texture2d)(float,float,float,float) r8.xyzw, r0.xyxx, t15.wxyz, s0
sample_indexable(texture2d)(float,float,float,float) r9.xyz, r0.xyxx, t21.xyzw, s0
dp3 r7.w, r9.xyzx, r9.xyzx
sqrt r7.w, r7.w
add r9.xyz, -v2.xyzx, v6.xyzx
dp3 r9.w, r9.xyzx, r9.xyzx
rsq r9.w, r9.w
mul r10.xyz, r9.wwww, r9.xyzx
dp3 r10.w, -r10.xyzx, r1.xyzx
mad r11.x, r10.w, l(0.500000), l(0.500000)
dp3 r11.y, -r1.xyzx, -r10.xyzx
max r11.y, r11.y, l(0.000000)
dp3 r11.z, -r10.xyzx, -r10.xyzx
mad r11.z, r11.z, l(0.500000), l(0.500000)
mul r11.z, r11.z, cb5[3].x
mad r11.y, cb5[3].x, r11.y, r11.z
dp3 r10.z, r1.xyzx, r10.xyzx
max r11.z, r10.z, l(0.000000)
add r11.w, -r11.z, l(1.000000)
mul r11.w, r11.w, r11.w
max r10.w, r10.w, l(0.000000)
mad r9.xyz, -r9.xyzx, r9.wwww, r1.xyzx
dp3 r9.w, r9.xyzx, r9.xyzx
rsq r9.w, r9.w
mul r9.xyz, r9.wwww, r9.xyzx
dp3_sat r1.z, r1.xyzx, r9.xyzx
lt r9.x, r11.z, l(0.800000)
lt r9.y, l(2.000000), cb5[3].x
and r9.x, r9.y, r9.x
mov r12.xyz, v2.xyzx
mov r12.w, l(1.000000)
mov r9.yzw, l(0,0,0,0)
mov r13.xyz, l(0,0,0,0)
mov r14.xyz, l(0,0,0,0)
mov r15.xyz, l(0,0,0,0)
mov r11.z, r4.w
loop 
  uge r13.w, r11.z, r0.w
  breakc_nz r13.w
  ld_indexable(buffer)(uint,uint,uint,uint) r13.w, r11.zzzz, t4.yzwx
  ld_indexable(buffer)(float,float,float,float) r16.xyzw, r13.wwww, t2.xyzw
  add r16.xyz, r16.xyzx, -v2.xyzx
  dp3 r14.w, r16.xyzx, r16.xyzx
  sqrt r15.w, r14.w
  lt r17.x, r15.w, r16.w
  if_nz r17.x
    rsq r17.x, r14.w
    mul r17.xyzw, r16.yzxz, r17.xxxx
    div r18.x, r15.w, r16.w
    mul r18.y, r18.x, r18.x
    mad r18.y, -r18.y, r18.y, l(1.000000)
    mul r18.y, r18.y, r18.y
    min r18.y, r18.y, l(1.000000)
    mul r16.w, r16.w, r18.y
    add r14.w, r14.w, l(1.000000)
    div r14.w, r16.w, r14.w
    ld_indexable(buffer)(float,float,float,float) r18.yzw, r13.wwww, t3.wxyz
    dp3_sat r16.w, r17.zxwz, r2.xyzx
    mul r19.xyz, r16.wwww, r18.yzwy
    mul r19.xyz, r14.wwww, r19.xyzx
    mul r19.xyz, r19.xyzx, cb5[1].yyyy
    mul r19.xyz, r19.xyzx, l(10.000000, 10.000000, 10.000000, 0.000000)
    mad r20.xyz, r3.xyzx, r0.zzzz, r16.xyzx
    dp3 r16.w, r20.xyzx, r20.xyzx
    rsq r16.w, r16.w
    mul r20.xyz, r16.wwww, r20.xyzx
    dp3_sat r16.w, r2.xyzx, r16.xyzx
    dp3_sat r19.w, r2.xyzx, r20.xyzx
    dp3_sat r16.x, r16.xyzx, r20.xyzx
    mul r16.y, r19.w, r19.w
    mad r16.y, r16.y, r5.z, l(1.000000)
    mul r16.y, r16.y, r16.y
    mul r16.y, r16.y, l(3.141590)
    div r16.y, r5.y, r16.y
    add r16.x, -r16.x, l(1.000000)
    mul r16.z, r16.x, r16.x
    mul r16.z, r16.z, r16.z
    mul r16.x, r16.z, r16.x
    mad r16.x, r7.x, r16.x, cb5[10].y
    mad r16.z, r16.w, r5.w, r7.y
    div r16.z, l(1.000000, 1.000000, 1.000000, 1.000000), r16.z
    mul r16.z, r5.x, r16.z
    mul r16.y, r16.y, r16.w
    mul r16.x, r16.x, r16.y
    mul r16.x, r16.z, r16.x
    mul r16.xyz, r16.xxxx, r18.yzwy
    mul r16.xyz, r14.wwww, r16.xyzx
    mul r16.xyz, r16.xyzx, l(10.000000, 10.000000, 10.000000, 0.000000)
    dp3_sat r16.w, r17.zxwz, -r2.xyzx
    mul r18.yzw, r16.wwww, r18.yyzw
    mul r18.yzw, r14.wwww, r18.yyzw
    mul r18.yzw, r18.yyzw, cb5[1].yyyy
    mul r18.yzw, r18.yyzw, l(0.000000, 10.000000, 10.000000, 10.000000)
    if_nz cb5[6].z
      mul r20.xyz, r19.xyzx, r16.xyzx
      add r20.xyz, r20.xyzx, r20.xyzx
    else 
      mul r21.xyz, r19.xyzx, r16.xyzx
      mul r20.xyz, r4.xyzx, r21.xyzx
    endif 
    lt r21.xyzw, |r17.xyzw|, |r17.zzxx|
    ge r17.xy, -r17.zxzz, l(0.000000, 0.000000, 0.000000, 0.000000)
    and r21.xy, r21.ywyy, r21.xzxx
    movc r17.xy, r17.xyxx, l(0,2,0,0), l(1,3,0,0)
    ge r14.w, r17.w, l(0.000000)
    movc r14.w, r14.w, l(4), l(5)
    movc r14.w, r21.y, r17.y, r14.w
    movc r14.w, r21.x, r17.x, r14.w
    ishl r16.w, r14.w, l(2)
    imad r16.w, r13.w, l(24), r16.w
    dp4 r17.x, r12.xyzw, cb3[r16.w + 0].xyzw
    dp4 r17.y, r12.xyzw, cb3[r16.w + 1].xyzw
    dp4 r17.z, r12.xyzw, cb3[r16.w + 2].xyzw
    dp4 r16.w, r12.xyzw, cb3[r16.w + 3].xyzw
    div r17.xyz, r17.xyzx, r16.wwww
    mad r17.xy, r17.xyxx, l(0.500000, -0.500000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
    itof r14.w, r14.w
    add r14.w, r14.w, r17.x
    mul r21.x, r14.w, l(0.166667)
    utof r14.w, r13.w
    add r14.w, r14.w, r17.y
    mul r21.y, r14.w, l(0.083333)
    mul_sat r14.w, r18.x, l(5.000000)
    mad r14.w, r14.w, l(-9.900000), l(10.000000)
    mad r14.w, -r14.w, cb3[336].w, r17.z
    sample_c_lz_indexable(-3,-3,0)(texture2d)(float,float,float,float) r16.w, r21.xyxx, t13.xxxx, s1, r14.w
    sample_c_lz_indexable(-3,-2,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(-3,-1,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(-3,0,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(-3,1,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(-3,2,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(-3,3,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(-2,-3,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(-2,-2,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(-2,-1,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(-2,0,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(-2,1,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(-2,2,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(-2,3,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(-1,-3,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(-1,-2,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(-1,-1,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(-1,0,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(-1,1,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(-1,2,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(-1,3,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(0,-3,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(0,-2,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(0,-1,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(0,0,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(0,1,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(0,2,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(0,3,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(1,-3,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(1,-2,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(1,-1,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(1,0,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(1,1,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(1,2,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(1,3,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(2,-3,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(2,-2,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(2,-1,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(2,0,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(2,1,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(2,2,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(2,3,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(3,-3,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(3,-2,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(3,-1,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(3,0,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(3,1,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(3,2,0)(texture2d)(float,float,float,float) r17.x, r21.xyxx, t13.xxxx, s1, r14.w
    add r16.w, r16.w, r17.x
    sample_c_lz_indexable(3,3,0)(texture2d)(float,float,float,float) r14.w, r21.xyxx, t13.xxxx, s1, r14.w
    add r14.w, r14.w, r16.w
    mul r14.w, r14.w, l(0.020408)
    mul r17.xyz, r14.wwww, r19.xyzx
    mul r19.xyz, r14.wwww, r20.xyzx
    mul r18.xyz, r14.wwww, r18.yzwy
    mul r16.xyz, r14.wwww, r16.xyzx
  else 
    mov r17.xyz, l(0,0,0,0)
    mov r19.xyz, l(0,0,0,0)
    mov r18.xyz, l(0,0,0,0)
    mov r16.xyz, l(0,0,0,0)
  endif 
  mad r17.xyz, r7.zzzz, r17.xyzx, r17.xyzx
  mad r18.xyz, r7.zzzz, r18.xyzx, r18.xyzx
  mad r19.xyz, r7.zzzz, r19.xyzx, r19.xyzx
  mad r16.xyz, r7.zzzz, r16.xyzx, r16.xyzx
  if_nz cb5[8].z
    div r14.w, l(1.000000, 1.000000, 1.000000, 1.000000), r15.w
    mul r14.w, r14.w, l(10.000000)
    mul r15.w, r11.y, r14.w
    mul r20.xyz, r15.wwww, cb5[2].xyzx
    mul r20.xyz, r7.wwww, r20.xyzx
    if_nz r9.x
      mul r21.xyz, r20.xyzx, l(0.066667, 0.066667, 0.066667, 0.000000)
      mul r17.xyz, r17.xyzx, r21.xyzx
      mul r19.xyz, r19.xyzx, r21.xyzx
      mul r18.xyz, r18.xyzx, r21.xyzx
      mul r16.xyz, r16.xyzx, r21.xyzx
    else 
      ld_indexable(buffer)(float,float,float,float) r21.xyz, r13.wwww, t3.xyzw
      mul r13.w, r11.x, r14.w
      mad r20.xyz, r13.wwww, r8.yzwy, r20.xyzx
      mul r13.w, r1.z, r14.w
      mul r22.xyz, r10.wwww, r19.xyzx
      mul r22.xyz, r11.wwww, r22.xyzx
      mul r22.xyz, r22.xyzx, cb5[3].zzzz
      mad r22.xyz, r22.xyzx, r14.wwww, r20.xyzx
      mul r23.xyz, r19.xyzx, r13.wwww
      mad r22.xyz, r23.xyzx, l(0.050000, 0.050000, 0.050000, 0.000000), r22.xyzx
      mul r22.xyz, r21.xyzx, r22.xyzx
      mul r17.xyz, r17.xyzx, r22.xyzx
      mul r19.xyz, r19.xyzx, r22.xyzx
      mul r22.xyz, r10.wwww, r16.xyzx
      mul r22.xyz, r11.wwww, r22.xyzx
      mul r22.xyz, r22.xyzx, cb5[3].zzzz
      mad r20.xyz, r22.xyzx, r14.wwww, r20.xyzx
      mul r22.xyz, r16.xyzx, r13.wwww
      mad r20.xyz, r22.xyzx, l(0.050000, 0.050000, 0.050000, 0.000000), r20.xyzx
      mul r20.xyz, r21.xyzx, r20.xyzx
      mul r18.xyz, r18.xyzx, r20.xyzx
      mul r16.xyz, r16.xyzx, r20.xyzx
    endif 
  endif 
  add r9.yzw, r9.yyzw, r17.xxyz
  add r13.xyz, r13.xyzx, r19.xyzx
  add r14.xyz, r14.xyzx, r18.xyzx
  add r15.xyz, r15.xyzx, r16.xyzx
  iadd r11.z, r11.z, l(1)
endloop 
ld_indexable(buffer)(uint,uint,uint,uint) r0.w, r1.wwww, t8.yzwx
ld_indexable(buffer)(uint,uint,uint,uint) r1.w, r6.xxxx, t8.yzwx
ishl r0.w, r0.w, l(16)
or r0.w, r1.w, r0.w
lt r0.w, r2.w, r0.w
movc r1.w, r0.w, r6.y, r3.w
ld_indexable(buffer)(uint,uint,uint,uint) r2.w, r6.zzzz, t8.yzwx
ld_indexable(buffer)(uint,uint,uint,uint) r3.w, r6.wwww, t8.yzwx
movc r0.w, r0.w, r2.w, r3.w
iadd r0.w, r1.w, r0.w
mov r6.xyz, v2.xyzx
mov r6.w, l(1.000000)
mov r12.xyz, r9.yzwy
mov r16.xyz, r13.xyzx
mov r17.xyz, r14.xyzx
mov r18.xyz, r15.xyzx
mov r2.w, r1.w
loop 
  uge r3.w, r2.w, r0.w
  breakc_nz r3.w
  ld_indexable(buffer)(uint,uint,uint,uint) r3.w, r2.wwww, t8.yzwx
  ld_indexable(buffer)(float,float,float,float) r19.xyzw, r3.wwww, t5.xyzw
  ld_indexable(buffer)(float,float,float,float) r20.xyzw, r3.wwww, t7.xyzw
  mad r4.w, -r20.x, r20.x, l(1.000000)
  mad r4.w, -r20.y, r20.y, r4.w
  sqrt r4.w, r4.w
  lt r11.z, l(0.000000), r20.z
  movc r21.z, r11.z, r4.w, -r4.w
  mov r21.xy, r20.xyxx
  mad r22.xyz, -r19.wwww, r21.xyzx, r19.xyzx
  add r22.xyz, r22.xyzx, -v2.xyzx
  dp3 r4.w, r22.xyzx, r22.xyzx
  rsq r12.w, r4.w
  mul r23.xyz, r12.wwww, r22.xyzx
  sqrt r12.w, r4.w
  dp3 r13.w, -r23.xyzx, r21.xyzx
  movc r11.z, r11.z, r20.z, -r20.z
  lt r14.w, r12.w, r20.w
  lt r15.w, r11.z, r13.w
  and r14.w, r14.w, r15.w
  if_nz r14.w
    add r13.w, -r11.z, r13.w
    add r11.z, -r11.z, l(1.000000)
    div r11.z, r13.w, r11.z
    mul r11.z, r11.z, r11.z
    div r12.w, r12.w, r20.w
    mul r12.w, r12.w, r12.w
    mad r12.w, -r12.w, r12.w, l(1.000000)
    mul r12.w, r12.w, r12.w
    min r12.w, r12.w, l(1.000000)
    mul r12.w, r12.w, r20.w
    add r4.w, r4.w, l(1.000000)
    div r4.w, r12.w, r4.w
    ld_indexable(buffer)(float,float,float,float) r20.xyz, r3.wwww, t6.xyzw
    dp3_sat r12.w, r23.xyzx, r2.xyzx
    mul r21.xyz, r12.wwww, r20.xyzx
    mul r21.xyz, r4.wwww, r21.xyzx
    mul r21.xyz, r11.zzzz, r21.xyzx
    mul r21.xyz, r21.xyzx, cb5[1].yyyy
    mul r21.xyz, r21.xyzx, l(10.000000, 10.000000, 10.000000, 0.000000)
    mad r24.xyz, r3.xyzx, r0.zzzz, r22.xyzx
    dp3 r12.w, r24.xyzx, r24.xyzx
    rsq r12.w, r12.w
    mul r24.xyz, r12.wwww, r24.xyzx
    dp3_sat r12.w, r2.xyzx, r22.xyzx
    dp3_sat r13.w, r2.xyzx, r24.xyzx
    dp3_sat r14.w, r22.xyzx, r24.xyzx
    mul r13.w, r13.w, r13.w
    mad r13.w, r13.w, r5.z, l(1.000000)
    mul r13.w, r13.w, r13.w
    mul r13.w, r13.w, l(3.141590)
    div r13.w, r5.y, r13.w
    add r14.w, -r14.w, l(1.000000)
    mul r15.w, r14.w, r14.w
    mul r15.w, r15.w, r15.w
    mul r14.w, r14.w, r15.w
    mad r14.w, r7.x, r14.w, cb5[10].y
    mad r15.w, r12.w, r5.w, r7.y
    div r15.w, l(1.000000, 1.000000, 1.000000, 1.000000), r15.w
    mul r15.w, r5.x, r15.w
    mul r12.w, r12.w, r13.w
    mul r12.w, r14.w, r12.w
    mul r12.w, r15.w, r12.w
    mul r22.xyz, r12.wwww, r20.xyzx
    mul r22.xyz, r4.wwww, r22.xyzx
    mul r22.xyz, r11.zzzz, r22.xyzx
    mul r22.xyz, r22.xyzx, l(10.000000, 10.000000, 10.000000, 0.000000)
    dp3_sat r12.w, r23.xyzx, -r2.xyzx
    mul r20.xyz, r12.wwww, r20.xyzx
    mul r20.xyz, r4.wwww, r20.xyzx
    mul r20.xyz, r11.zzzz, r20.xyzx
    mul r20.xyz, r20.xyzx, cb5[1].yyyy
    if_nz cb5[6].z
      mul r23.xyz, r21.xyzx, r22.xyzx
      add r23.xyz, r23.xyzx, r23.xyzx
    else 
      mul r24.xyz, r21.xyzx, r22.xyzx
      mul r23.xyz, r4.xyzx, r24.xyzx
    endif 
    ishl r4.w, r3.w, l(2)
    dp4 r24.x, r6.xyzw, cb3[r4.w + 288].xyzw
    dp4 r24.y, r6.xyzw, cb3[r4.w + 289].xyzw
    dp4 r24.z, r6.xyzw, cb3[r4.w + 290].xyzw
    dp4 r4.w, r6.xyzw, cb3[r4.w + 291].xyzw
    div r24.xyz, r24.xyzx, r4.wwww
    mad r25.yz, r24.xxyx, l(0.000000, 0.500000, -0.500000, 0.000000), l(0.000000, 0.500000, 0.500000, 0.000000)
    utof r4.w, r3.w
    add r4.w, r4.w, r25.y
    mul r25.x, r4.w, l(0.083333)
    mad r4.w, -cb3[336].w, l(6.000000), r24.z
    sample_c_lz_indexable(-3,-3,0)(texture2d)(float,float,float,float) r11.z, r25.xzxx, t14.xxxx, s1, r4.w
    sample_c_lz_indexable(-3,-2,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(-3,-1,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(-3,0,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(-3,1,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(-3,2,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(-3,3,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(-2,-3,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(-2,-2,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(-2,-1,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(-2,0,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(-2,1,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(-2,2,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(-2,3,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(-1,-3,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(-1,-2,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(-1,-1,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(-1,0,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(-1,1,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(-1,2,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(-1,3,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(0,-3,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(0,-2,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(0,-1,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(0,0,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(0,1,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(0,2,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(0,3,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(1,-3,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(1,-2,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(1,-1,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(1,0,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(1,1,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(1,2,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(1,3,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(2,-3,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(2,-2,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(2,-1,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(2,0,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(2,1,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(2,2,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(2,3,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(3,-3,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(3,-2,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(3,-1,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(3,0,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(3,1,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(3,2,0)(texture2d)(float,float,float,float) r12.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r11.z, r11.z, r12.w
    sample_c_lz_indexable(3,3,0)(texture2d)(float,float,float,float) r4.w, r25.xzxx, t14.xxxx, s1, r4.w
    add r4.w, r4.w, r11.z
    mul r4.w, r4.w, l(0.020408)
    mul r21.xyz, r4.wwww, r21.xyzx
    mul r23.xyz, r4.wwww, r23.xyzx
    mul r20.xyz, r4.wwww, r20.xyzx
    mul r22.xyz, r4.wwww, r22.xyzx
  else 
    mov r21.xyz, l(0,0,0,0)
    mov r23.xyz, l(0,0,0,0)
    mov r20.xyz, l(0,0,0,0)
    mov r22.xyz, l(0,0,0,0)
  endif 
  mad r21.xyz, r7.zzzz, r21.xyzx, r21.xyzx
  mad r20.xyz, r7.zzzz, r20.xyzx, r20.xyzx
  mad r23.xyz, r7.zzzz, r23.xyzx, r23.xyzx
  mad r22.xyz, r7.zzzz, r22.xyzx, r22.xyzx
  if_nz cb5[8].z
    add r19.xyz, r19.xyzx, -v2.xyzx
    dp3 r4.w, r19.xyzx, r19.xyzx
    sqrt r4.w, r4.w
    div r4.w, l(1.000000, 1.000000, 1.000000, 1.000000), r4.w
    mul r4.w, r4.w, l(10.000000)
    mul r11.z, r4.w, r11.y
    mul r19.xyz, r11.zzzz, cb5[2].xyzx
    mul r19.xyz, r7.wwww, r19.xyzx
    if_nz r9.x
      mul r24.xyz, r19.xyzx, l(0.066667, 0.066667, 0.066667, 0.000000)
      mul r21.xyz, r21.xyzx, r24.xyzx
      mul r23.xyz, r23.xyzx, r24.xyzx
      mul r20.xyz, r20.xyzx, r24.xyzx
      mul r22.xyz, r22.xyzx, r24.xyzx
    else 
      ld_indexable(buffer)(float,float,float,float) r24.xyz, r3.wwww, t6.xyzw
      mul r3.w, r4.w, r11.x
      mad r19.xyz, r3.wwww, r8.yzwy, r19.xyzx
      mul r3.w, r1.z, r4.w
      mul r25.xyz, r10.wwww, r23.xyzx
      mul r25.xyz, r11.wwww, r25.xyzx
      mul r25.xyz, r25.xyzx, cb5[3].zzzz
      mad r25.xyz, r25.xyzx, r4.wwww, r19.xyzx
      mul r26.xyz, r23.xyzx, r3.wwww
      mad r25.xyz, r26.xyzx, l(0.050000, 0.050000, 0.050000, 0.000000), r25.xyzx
      mul r25.xyz, r24.xyzx, r25.xyzx
      mul r21.xyz, r21.xyzx, r25.xyzx
      mul r23.xyz, r23.xyzx, r25.xyzx
      mul r25.xyz, r10.wwww, r22.xyzx
      mul r25.xyz, r11.wwww, r25.xyzx
      mul r25.xyz, r25.xyzx, cb5[3].zzzz
      mad r19.xyz, r25.xyzx, r4.wwww, r19.xyzx
      mul r25.xyz, r22.xyzx, r3.wwww
      mad r19.xyz, r25.xyzx, l(0.050000, 0.050000, 0.050000, 0.000000), r19.xyzx
      mul r19.xyz, r24.xyzx, r19.xyzx
      mul r20.xyz, r19.xyzx, r20.xyzx
      mul r22.xyz, r19.xyzx, r22.xyzx
    endif 
  endif 
  add r12.xyz, r12.xyzx, r21.xyzx
  add r16.xyz, r16.xyzx, r23.xyzx
  add r17.xyz, r17.xyzx, r20.xyzx
  add r18.xyz, r18.xyzx, r22.xyzx
  iadd r2.w, r2.w, l(1)
endloop 
add r2.yzw, r12.xxyz, r12.xxyz
add r3.xyz, r17.xyzx, r17.xyzx
mul r0.zw, r2.xxxx, l(0.000000, 0.000000, 0.250000, -0.250000)
mad r1.zw, -r2.xxxx, l(0.000000, 0.000000, 0.250000, -0.250000), l(0.000000, 0.000000, 1.000000, 1.000000)
mul r4.xyz, r1.zzzz, cb2[21].xyzx
mad r4.xyz, cb2[20].xyzx, r0.zzzz, r4.xyzx
mul r5.xyz, r1.wwww, cb2[21].xyzx
mad r5.xyz, cb2[20].xyzx, r0.wwww, r5.xyzx
mul r6.xyz, r8.yzwy, l(0.250000, 0.250000, 0.250000, 0.000000)
mad r2.xyz, r2.yzwy, r4.xyzx, r6.xyzx
mad r3.xyz, r3.xyzx, r5.xyzx, r6.xyzx
mad r2.xyz, r16.xyzx, l(8.000000, 8.000000, 8.000000, 0.000000), r2.xyzx
mad r3.xyz, r18.xyzx, l(8.000000, 8.000000, 8.000000, 0.000000), r3.xyzx
mad r2.xyz, r3.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r2.xyzx
if_nz cb5[7].z
  resinfo_indexable(texture2d)(float,float,float,float)_uint r0.zw, l(0), t15.zwxy
  utof r3.xyzw, r0.zwzw
  ld_indexable(texture2d)(float,float,float,float) r4.xyz, l(0, 0, 0, 0), t15.xyzw
  mad r3.xyzw, r0.xyxy, r3.xyzw, l(-0.500000, -0.500000, 0.500000, 0.500000)
  ftoi r5.xyzw, r3.zyxy
  mov r6.xy, r5.zwzz
  mov r6.zw, l(0,0,0,0)
  ld_indexable(texture2d)(float,float,float,float) r6.xyzw, r6.xyzw, t15.xyzw
  mov r5.zw, l(0,0,0,0)
  ld_indexable(texture2d)(float,float,float,float) r5.xyzw, r5.xyzw, t15.xyzw
  ftoi r7.xyzw, r3.zwxw
  mov r9.xy, r7.zwzz
  mov r9.zw, l(0,0,0,0)
  ld_indexable(texture2d)(float,float,float,float) r9.xyzw, r9.xyzw, t15.xyzw
  mov r7.zw, l(0,0,0,0)
  ld_indexable(texture2d)(float,float,float,float) r7.xyzw, r7.xyzw, t15.xyzw
  eq r6.xyz, r6.xyzx, r4.xyzx
  and r0.z, r6.y, r6.x
  and r0.z, r6.z, r0.z
  movc r0.z, r0.z, l(0), r6.w
  eq r5.xyz, r5.xyzx, r4.xyzx
  and r0.w, r5.y, r5.x
  and r0.w, r5.z, r0.w
  movc r0.w, r0.w, l(0), r5.w
  eq r5.xyz, r9.xyzx, r4.xyzx
  and r1.z, r5.y, r5.x
  and r1.z, r5.z, r1.z
  movc r1.z, r1.z, l(0), r9.w
  eq r4.xyz, r7.xyzx, r4.xyzx
  and r1.w, r4.y, r4.x
  and r1.w, r4.z, r1.w
  movc r1.w, r1.w, l(0), r7.w
  frc r3.xy, r3.xyxx
  add r0.w, -r0.z, r0.w
  mad r0.z, r0.w, r3.x, r0.z
  add r0.w, -r1.z, r1.w
  mad r0.w, r0.w, r3.x, r1.z
  add r0.w, -r0.z, r0.w
  mad r8.x, r0.w, r3.y, r0.z
endif 
add r2.xyz, r2.xyzx, r2.xyzx
if_nz cb5[7].w
  add r0.z, r10.z, r10.z
  mad r0.zw, r1.xxxy, -r0.zzzz, r10.xxxy
  mad r1.z, -r10.z, r10.z, l(1.000000)
  mad r1.z, -r1.z, l(0.980100), l(1.000000)
  sqrt r1.w, r1.z
  mad r1.w, r10.z, l(0.990000), r1.w
  ge r1.z, r1.z, l(0.000000)
  mul r1.xy, r1.xyxx, r1.wwww
  mad r1.xy, r10.xyxx, l(0.990000, 0.990000, 0.000000, 0.000000), -r1.xyxx
  and r1.xy, r1.xyxx, r1.zzzz
  sample_indexable(texture2d)(float,float,float,float) r1.xyz, r1.xyxx, t19.xyzw, s0
  sample_indexable(texture2d)(float,float,float,float) r3.xyz, r0.zwzz, t19.xyzw, s0
  if_nz cb5[8].w
    sample_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t19.wxyz, s0
    add r0.yzw, -r1.xxyz, r3.xxyz
    mad r0.yzw, r0.yyzw, l(0.000000, 0.500000, 0.500000, 0.500000), r1.xxyz
    div r0.yzw, r0.yyzw, cb5[2].wwww
    mul r0.xyz, r0.yzwy, r0.xxxx
    dp3 r0.w, r2.xyzx, r2.xyzx
    mul r0.xyz, r0.wwww, r0.xyzx
    mul o0.xyz, r0.xyzx, r2.xyzx
  else 
    add r0.xyz, -r1.xyzx, r3.xyzx
    mad r0.xyz, r0.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r1.xyzx
    div r0.xyz, r0.xyzx, cb5[2].wwww
    dp3 r0.w, r2.xyzx, r2.xyzx
    mad o0.xyz, r0.xyzx, r0.wwww, r2.xyzx
  endif 
else 
  mov o0.xyz, r2.xyzx
endif 
min o0.w, r8.x, cb5[1].w
ret 
// Approximately 724 instruction slots used
