//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer TexInfo
// {
//
//   float4 f4ColorEffect;              // Offset:    0 Size:    16 [unused]
//   float fBlurStrength;               // Offset:   16 Size:     4 [unused]
//   uint uBlur;                        // Offset:   20 Size:     4 [unused]
//   uint uEnhancedEdges;               // Offset:   24 Size:     4 [unused]
//   uint uMeanFilter;                  // Offset:   28 Size:     4 [unused]
//   float fBloomOriginalIntensity;     // Offset:   32 Size:     4 [unused]
//   float fBloomIntensity;             // Offset:   36 Size:     4 [unused]
//   float fBloomOriginalSaturation;    // Offset:   40 Size:     4 [unused]
//   float fBloomSaturation;            // Offset:   44 Size:     4 [unused]
//   float fRayExposure;                // Offset:   48 Size:     4
//   float fRayDecay;                   // Offset:   52 Size:     4
//   float fRayDensity;                 // Offset:   56 Size:     4
//   float fRayWeight;                  // Offset:   60 Size:     4
//   float fTimeDelta;                  // Offset:   64 Size:     4 [unused]
//   float fBloomBlurDistance;          // Offset:   68 Size:     4 [unused]
//   float fDoFFar;                     // Offset:   72 Size:     4 [unused]
//   float fDoFNear;                    // Offset:   76 Size:     4 [unused]
//   float2 f2RayLightPos;              // Offset:   80 Size:     8
//   float2 f2rcpFrame;                 // Offset:   88 Size:     8
//   float4 f4rcpFrameOpt;              // Offset:   96 Size:    16 [unused]
//   float4 f4DoFParams;                // Offset:  112 Size:    16 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// linearSampler                     sampler      NA          NA    1        1
// pointSampler                      sampler      NA          NA    2        1
// tex2D[7]                          texture  float4          2d   22        1
// godRayTex                         texture  float4          2d   24        1
// TexInfo                           cbuffer      NA          NA    7        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_POSITION              0   xyzw        0      POS  float       
// TEXCOORD                 0   xy          1     NONE  float   xy  
// TEXCOORD                 1     zw        1     NONE  float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_TARGET                0   xyzw        0   TARGET  float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb7[6], immediateIndexed
dcl_sampler s1, mode_default
dcl_sampler s2, mode_default
dcl_resource_texture2d (float,float,float,float) t22
dcl_resource_texture2d (float,float,float,float) t24
dcl_input_ps linear v1.xy
dcl_output o0.xyzw
dcl_temps 6
sample_indexable(texture2d)(float,float,float,float) r0.xyzw, v1.xyxx, t22.xyzw, s1
add r1.xy, cb7[5].zwzz, cb7[5].xyxx
add r1.xy, -r1.xyxx, v1.xyxx
mul r2.xyz, l(0.006667, 0.500000, 0.500000, 0.000000), cb7[3].zwyz
mad r1.zw, -r1.xxxy, r2.xxxx, v1.xxxy
sample_indexable(texture2d)(float,float,float,float) r3.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r3.xyzw, r2.yyyy, r0.xyzw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r1.zwzz, t24.xyzw, s2
mad r1.zw, -r1.xxxy, r2.xxxx, r1.zzzw
mad r3.xyzw, r4.xyzw, r2.yyyy, r3.xyzw
mul r2.yz, r2.zzzz, cb7[3].wwyw
mad r4.xy, -r1.xyxx, r2.xxxx, r1.zwzz
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r1.zwzz, t24.xyzw, s2
mad r3.xyzw, r5.xyzw, r2.yyyy, r3.xyzw
mul r1.zw, r2.zzzz, cb7[3].wwwy
mad r2.yz, -r1.xxyx, r2.xxxx, r4.xxyx
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r4.xyxx, t24.xyzw, s2
mad r3.xyzw, r4.xyzw, r1.zzzz, r3.xyzw
mul r1.zw, r1.wwww, cb7[3].wwwy
mad r4.xy, -r1.xyxx, r2.xxxx, r2.yzyy
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r2.yzyy, t24.xyzw, s2
mad r3.xyzw, r5.xyzw, r1.zzzz, r3.xyzw
mul r1.zw, r1.wwww, cb7[3].wwwy
mad r2.yz, -r1.xxyx, r2.xxxx, r4.xxyx
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r4.xyxx, t24.xyzw, s2
mad r3.xyzw, r4.xyzw, r1.zzzz, r3.xyzw
mul r1.zw, r1.wwww, cb7[3].wwwy
mad r4.xy, -r1.xyxx, r2.xxxx, r2.yzyy
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r2.yzyy, t24.xyzw, s2
mad r3.xyzw, r5.xyzw, r1.zzzz, r3.xyzw
mul r1.zw, r1.wwww, cb7[3].wwwy
mad r2.yz, -r1.xxyx, r2.xxxx, r4.xxyx
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r4.xyxx, t24.xyzw, s2
mad r3.xyzw, r4.xyzw, r1.zzzz, r3.xyzw
mul r1.zw, r1.wwww, cb7[3].wwwy
mad r4.xy, -r1.xyxx, r2.xxxx, r2.yzyy
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r2.yzyy, t24.xyzw, s2
mad r3.xyzw, r5.xyzw, r1.zzzz, r3.xyzw
mul r1.zw, r1.wwww, cb7[3].wwwy
mad r2.yz, -r1.xxyx, r2.xxxx, r4.xxyx
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r4.xyxx, t24.xyzw, s2
mad r3.xyzw, r4.xyzw, r1.zzzz, r3.xyzw
mul r1.zw, r1.wwww, cb7[3].wwwy
mad r4.xy, -r1.xyxx, r2.xxxx, r2.yzyy
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r2.yzyy, t24.xyzw, s2
mad r3.xyzw, r5.xyzw, r1.zzzz, r3.xyzw
mul r1.zw, r1.wwww, cb7[3].wwwy
mad r2.yz, -r1.xxyx, r2.xxxx, r4.xxyx
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r4.xyxx, t24.xyzw, s2
mad r3.xyzw, r4.xyzw, r1.zzzz, r3.xyzw
mul r1.zw, r1.wwww, cb7[3].wwwy
mad r4.xy, -r1.xyxx, r2.xxxx, r2.yzyy
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r2.yzyy, t24.xyzw, s2
mad r3.xyzw, r5.xyzw, r1.zzzz, r3.xyzw
mul r1.zw, r1.wwww, cb7[3].wwwy
mad r2.yz, -r1.xxyx, r2.xxxx, r4.xxyx
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r4.xyxx, t24.xyzw, s2
mad r3.xyzw, r4.xyzw, r1.zzzz, r3.xyzw
mul r1.zw, r1.wwww, cb7[3].wwwy
mad r4.xy, -r1.xyxx, r2.xxxx, r2.yzyy
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r2.yzyy, t24.xyzw, s2
mad r3.xyzw, r5.xyzw, r1.zzzz, r3.xyzw
mul r1.zw, r1.wwww, cb7[3].wwwy
mad r2.yz, -r1.xxyx, r2.xxxx, r4.xxyx
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r4.xyxx, t24.xyzw, s2
mad r3.xyzw, r4.xyzw, r1.zzzz, r3.xyzw
mul r1.zw, r1.wwww, cb7[3].wwwy
mad r4.xy, -r1.xyxx, r2.xxxx, r2.yzyy
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r2.yzyy, t24.xyzw, s2
mad r3.xyzw, r5.xyzw, r1.zzzz, r3.xyzw
mul r1.zw, r1.wwww, cb7[3].wwwy
mad r2.yz, -r1.xxyx, r2.xxxx, r4.xxyx
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r4.xyxx, t24.xyzw, s2
mad r3.xyzw, r4.xyzw, r1.zzzz, r3.xyzw
mul r1.zw, r1.wwww, cb7[3].wwwy
mad r4.xy, -r1.xyxx, r2.xxxx, r2.yzyy
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r2.yzyy, t24.xyzw, s2
mad r3.xyzw, r5.xyzw, r1.zzzz, r3.xyzw
mul r1.zw, r1.wwww, cb7[3].wwwy
mad r2.yz, -r1.xxyx, r2.xxxx, r4.xxyx
sample_indexable(texture2d)(float,float,float,float) r4.xyzw, r4.xyxx, t24.xyzw, s2
mad r3.xyzw, r4.xyzw, r1.zzzz, r3.xyzw
mul r1.zw, r1.wwww, cb7[3].wwwy
mad r4.xy, -r1.xyxx, r2.xxxx, r2.yzyy
sample_indexable(texture2d)(float,float,float,float) r5.xyzw, r2.yzyy, t24.xyzw, s2
mad r3.xyzw, r5.xyzw, r1.zzzz, r3.xyzw
mul r1.zw, r1.wwww, cb7[3].wwwy
mad r1.xy, -r1.xyxx, r2.xxxx, r4.xyxx
sample_indexable(texture2d)(float,float,float,float) r2.xyzw, r4.xyxx, t24.xyzw, s2
mad r2.xyzw, r2.xyzw, r1.zzzz, r3.xyzw
mul r1.z, r1.w, cb7[3].w
sample_indexable(texture2d)(float,float,float,float) r3.xyzw, r1.xyxx, t24.xyzw, s2
mad r1.xyzw, r3.xyzw, r1.zzzz, r2.xyzw
mul r1.xyzw, r1.xyzw, cb7[3].xxxx
mad o0.xyzw, r1.xyzw, l(0.500000, 0.500000, 0.500000, 0.500000), r0.xyzw
ret 
// Approximately 606 instruction slots used
