//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
//   fxc /T ps_5_0 /O1 /E RenderSpritesPS /Fo
//    \\?\C:\Users\Jonas\VektoriaV13_Beta\dauwilliwasmacha\VektoriaApp\Shaders\Cache\Object\Release\RenderSpritesPS.obj
//    /Fe
//    \\?\C:\Users\Jonas\VektoriaV13_Beta\dauwilliwasmacha\VektoriaApp\Shaders\Cache\Error\RenderSpritesPS.txt
//    /Fc
//    \\?\C:\Users\Jonas\VektoriaV13_Beta\dauwilliwasmacha\VektoriaApp\Shaders\Cache\Assembly\426a788b.asm
//    \\?\C:\Users\Jonas\VektoriaV13_Beta\dauwilliwasmacha\VektoriaApp\shaders\Source\sprites.hlsl
//
//
// Buffer Definitions: 
//
// cbuffer TexInfo
// {
//
//   float4 f4ColorAmbient;             // Offset:    0 Size:    16 [unused]
//   float fA;                          // Offset:   16 Size:     4 [unused]
//   float fH;                          // Offset:   20 Size:     4 [unused]
//   float fBumpStrength;               // Offset:   24 Size:     4 [unused]
//   float frTransparency;              // Offset:   28 Size:     4 [unused]
//   float4 f4ColorSSS;                 // Offset:   32 Size:    16 [unused]
//   float4 f4SSSBRDFParams;            // Offset:   48 Size:    16 [unused]
//   uint uImage;                       // Offset:   64 Size:     4 [unused]
//   uint uGlow;                        // Offset:   68 Size:     4 [unused]
//   uint uSpecular;                    // Offset:   72 Size:     4 [unused]
//   uint uBump;                        // Offset:   76 Size:     4 [unused]
//   uint uImageBlack;                  // Offset:   80 Size:     4 [unused]
//   uint uGlowAsImage;                 // Offset:   84 Size:     4 [unused]
//   uint uSpecularAsImage;             // Offset:   88 Size:     4 [unused]
//   uint uHeightAsImage;               // Offset:   92 Size:     4 [unused]
//   uint uImageWhite;                  // Offset:   96 Size:     4 [unused]
//   uint uGlowWhite;                   // Offset:  100 Size:     4 [unused]
//   uint uSpecularWhite;               // Offset:  104 Size:     4 [unused]
//   uint uHeight;                      // Offset:  108 Size:     4 [unused]
//   uint uShadingOn;                   // Offset:  112 Size:     4 [unused]
//   uint uGlowAsAmbient;               // Offset:  116 Size:     4 [unused]
//   uint uChromaKeying;                // Offset:  120 Size:     4
//   uint uEnvironment;                 // Offset:  124 Size:     4 [unused]
//   uint uPOM;                         // Offset:  128 Size:     4 [unused]
//   uint uTexBRDF;                     // Offset:  132 Size:     4 [unused]
//   uint uTexSSS;                      // Offset:  136 Size:     4 [unused]
//   uint uReflectionMap;               // Offset:  140 Size:     4 [unused]
//   uint uixPos;                       // Offset:  144 Size:     4 [unused]
//   uint uiyPos;                       // Offset:  148 Size:     4 [unused]
//   uint uixPics;                      // Offset:  152 Size:     4 [unused]
//   uint uiyPics;                      // Offset:  156 Size:     4 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// linearSampler                     sampler      NA          NA    0        1
// tex2D[0]                          texture  float4          2d   15        1
// TexInfo                           cbuffer      NA          NA    5        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_POSITION              0   xyzw        0      POS  float       
// NORMAL                   0   xyz         1     NONE  float       
// TANGENT                  0   xyz         2     NONE  float       
// BITANGENT                0   xyz         3     NONE  float       
// TEXCOORD                 0   xy          4     NONE  float   xy  
// TEXCOORD                 2   xyzw        5     NONE  float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_Target                0   xyzw        0   TARGET  float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb5[8], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_texture2d (float,float,float,float) t15
dcl_input_ps linear v4.xy
dcl_output o0.xyzw
dcl_temps 7
if_nz cb5[7].z
  resinfo_indexable(texture2d)(float,float,float,float)_uint r0.xy, l(0), t15.xyzw
  utof r0.xyzw, r0.xyxy
  ld_indexable(texture2d)(float,float,float,float) r1.xyz, l(0, 0, 0, 0), t15.xyzw
  mad r0.xyzw, v4.xyxy, r0.xyzw, l(-0.500000, -0.500000, 0.500000, 0.500000)
  ftoi r2.xyzw, r0.zyxy
  mov r3.xy, r2.zwzz
  mov r3.zw, l(0,0,0,0)
  ld_indexable(texture2d)(float,float,float,float) r3.xyzw, r3.xyzw, t15.xyzw
  mov r2.zw, l(0,0,0,0)
  ld_indexable(texture2d)(float,float,float,float) r2.xyzw, r2.xyzw, t15.xyzw
  ftoi r4.xyzw, r0.zwxw
  mov r5.xy, r4.zwzz
  mov r5.zw, l(0,0,0,0)
  ld_indexable(texture2d)(float,float,float,float) r5.xyzw, r5.xyzw, t15.xyzw
  mov r4.zw, l(0,0,0,0)
  ld_indexable(texture2d)(float,float,float,float) r4.xyzw, r4.xyzw, t15.xyzw
  eq r6.xyz, r3.xyzx, r1.xyzx
  and r0.z, r6.y, r6.x
  and r0.z, r6.z, r0.z
  movc r3.xyzw, r0.zzzz, l(0,0,0,0), r3.xyzw
  eq r6.xyz, r2.xyzx, r1.xyzx
  and r0.z, r6.y, r6.x
  and r0.z, r6.z, r0.z
  movc r2.xyzw, r0.zzzz, l(0,0,0,0), r2.xyzw
  eq r6.xyz, r5.xyzx, r1.xyzx
  and r0.z, r6.y, r6.x
  and r0.z, r6.z, r0.z
  movc r5.xyzw, r0.zzzz, l(0,0,0,0), r5.xyzw
  eq r1.xyz, r4.xyzx, r1.xyzx
  and r0.z, r1.y, r1.x
  and r0.z, r1.z, r0.z
  movc r1.xyzw, r0.zzzz, l(0,0,0,0), r4.xyzw
  frc r0.xy, r0.xyxx
  add r2.xyzw, -r3.xyzw, r2.xyzw
  mad r2.xyzw, r2.xyzw, r0.xxxx, r3.xyzw
  add r1.xyzw, -r5.xyzw, r1.xyzw
  mad r1.xyzw, r1.xyzw, r0.xxxx, r5.xyzw
  add r1.xyzw, -r2.xyzw, r1.xyzw
  mad o0.xyzw, r1.xyzw, r0.yyyy, r2.xyzw
else 
  sample_indexable(texture2d)(float,float,float,float) o0.xyzw, v4.xyxx, t15.xyzw, s0
endif 
ret 
// Approximately 44 instruction slots used
