//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer cbPerFrame
// {
//
//   float4x4 g_mView;                  // Offset:    0 Size:    64 [unused]
//   float4x4 g_mViewInv;               // Offset:   64 Size:    64 [unused]
//   float4x4 g_mProjection;            // Offset:  128 Size:    64 [unused]
//   float4x4 g_mProjectionInv;         // Offset:  192 Size:    64 [unused]
//   float4x4 g_mProjectionInvViewport; // Offset:  256 Size:    64 [unused]
//   float4 g_f4AmbientColorUp;         // Offset:  320 Size:    16 [unused]
//   float4 g_f4AmbientColorDown;       // Offset:  336 Size:    16 [unused]
//   float3 g_f3CameraPos;              // Offset:  352 Size:    12 [unused]
//   float g_fAlphaTest;                // Offset:  364 Size:     4 [unused]
//   uint g_uNumLights;                 // Offset:  368 Size:     4 [unused]
//   uint g_uNumSpotLights;             // Offset:  372 Size:     4 [unused]
//   uint g_uWindowWidth;               // Offset:  376 Size:     4 [unused]
//   uint g_uWindowHeight;              // Offset:  380 Size:     4 [unused]
//   uint g_uMaxNumLightsPerTile;       // Offset:  384 Size:     4 [unused]
//   uint g_uMaxNumElementsPerTile;     // Offset:  388 Size:     4 [unused]
//   uint g_uNumTilesX;                 // Offset:  392 Size:     4 [unused]
//   uint g_uNumTilesY;                 // Offset:  396 Size:     4 [unused]
//   uint g_uMaxVPLs;                   // Offset:  400 Size:     4 [unused]
//   uint g_uMaxNumVPLsPerTile;         // Offset:  404 Size:     4 [unused]
//   uint g_uMaxNumVPLElementsPerTile;  // Offset:  408 Size:     4 [unused]
//   float g_fVPLSpotStrength;          // Offset:  412 Size:     4
//   float g_fVPLSpotRadius;            // Offset:  416 Size:     4
//   float g_fVPLPointStrength;         // Offset:  420 Size:     4 [unused]
//   float g_fVPLPointRadius;           // Offset:  424 Size:     4 [unused]
//   float g_fVPLRemoveBackFaceContrib; // Offset:  428 Size:     4 [unused]
//   float g_fVPLColorThreshold;        // Offset:  432 Size:     4
//   float g_fVPLBrightnessThreshold;   // Offset:  436 Size:     4
//   float g_fPerFramePad1;             // Offset:  440 Size:     4 [unused]
//   float g_fPerFramePad2;             // Offset:  444 Size:     4 [unused]
//
// }
//
// Resource bind info for g_invViewProjMatrices
// {
//
//   float4x4 $Element;                 // Offset:    0 Size:    64
//
// }
//
// Resource bind info for g_vplPositionBuffer
// {
//
//   float4 $Element;                   // Offset:    0 Size:    16
//
// }
//
// Resource bind info for g_VPLData
// {
//
//   struct SVPLData
//   {
//       
//       float4 f4Direction;            // Offset:    0
//       float4 f4Color;                // Offset:   16
//       float4 f4SourceLightDirection; // Offset:   32
//
//   } $Element;                        // Offset:    0 Size:    48
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// g_RSMDepthAtlas                   texture  float4          2d    0        1
// g_RSMNormalAtlas                  texture  float4          2d    1        1
// g_RSMDiffuseAtlas                 texture  float4          2d    2        1
// g_invViewProjMatrices             texture  struct         r/o    3        1
// g_spotLightCenterAndRadiusBuffer    texture  float4         buf    4        1
// g_spotLightColorBuffer            texture  float4         buf    5        1
// g_spotLightSpotParamsBuffer       texture  float4         buf    6        1
// g_vplPositionBuffer                   UAV  struct     r/w+cnt    0        1
// g_VPLData                             UAV  struct         r/w    1        1
// cbPerFrame                        cbuffer      NA          NA    2        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// no Input
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// no Output
cs_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb2[28], immediateIndexed
dcl_resource_texture2d (float,float,float,float) t0
dcl_resource_texture2d (float,float,float,float) t1
dcl_resource_texture2d (float,float,float,float) t2
dcl_resource_structured t3, 64 
dcl_resource_buffer (float,float,float,float) t4
dcl_resource_buffer (float,float,float,float) t5
dcl_resource_buffer (float,float,float,float) t6
dcl_uav_structured_opc u0, 16
dcl_uav_structured u1, 48
dcl_input vThreadID.xy
dcl_temps 7
dcl_thread_group 16, 16, 1
ishl r0.xy, vThreadID.xyxx, l(1, 1, 0, 0)
ubfe r1.x, l(27), l(4), vThreadID.x
mov r0.zw, l(0,0,0,0)
ld_indexable(texture2d)(float,float,float,float) r1.yzw, r0.xyww, t2.wxyz
utof r2.xy, r0.xyxx
mul r2.xy, r2.xyxx, l(0.031250, 0.031250, 0.000000, 0.000000)
frc r2.xy, r2.xyxx
ld_indexable(texture2d)(float,float,float,float) r3.z, r0.xyww, t0.yzxw
mad r2.xy, r2.xyxx, l(32.000000, 32.000000, 0.000000, 0.000000), l(0.500000, 0.500000, 0.000000, 0.000000)
mad r3.xy, r2.xyxx, l(0.062500, -0.062500, 0.000000, 0.000000), l(-1.000000, 1.000000, 0.000000, 0.000000)
ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r2.xyzw, r1.x, l(0), t3.xyzw
ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r4.xyzw, r1.x, l(16), t3.xyzw
ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r5.xyzw, r1.x, l(32), t3.xyzw
ld_structured_indexable(structured_buffer, stride=64)(mixed,mixed,mixed,mixed) r6.xyzw, r1.x, l(48), t3.xyzw
mov r3.w, l(1.000000)
dp4 r2.x, r3.xyzw, r2.xyzw
dp4 r2.y, r3.xyzw, r4.xyzw
dp4 r2.z, r3.xyzw, r5.xyzw
dp4 r2.w, r3.xyzw, r6.xyzw
div r2.xyz, r2.xyzx, r2.wwww
ld_indexable(buffer)(float,float,float,float) r3.xyz, r1.xxxx, t6.xyzw
mad r3.w, -r3.x, r3.x, l(1.000000)
mad r3.w, -r3.y, r3.y, r3.w
sqrt r3.w, r3.w
lt r4.x, l(0.000000), r3.z
movc r3.z, r4.x, r3.w, -r3.w
ld_indexable(buffer)(float,float,float,float) r4.xyzw, r1.xxxx, t4.xyzw
mad r4.xyz, -r4.wwww, r3.xyzx, r4.xyzx
add r4.xyz, r2.xyzx, -r4.xyzx
dp3 r3.w, r4.xyzx, r4.xyzx
sqrt r3.w, r3.w
div r3.w, r3.w, r4.w
add r3.w, -r3.w, l(1.000000)
mul r1.yzw, r1.yyzw, r3.wwww
dp3 r3.w, r1.yzwy, r1.yzwy
rsq r3.w, r3.w
mul r4.xyz, r1.yzwy, r3.wwww
lt r4.xyz, cb2[27].xxxx, r4.xyzx
or r3.w, r4.y, r4.x
or r3.w, r4.z, r3.w
if_nz r3.w
  ld_indexable(buffer)(float,float,float,float) r4.xyz, r1.xxxx, t5.xyzw
  mul r1.xyz, r1.yzwy, r4.xyzx
  mul r1.xyz, r1.xyzx, cb2[25].wwww
  dp3 r3.w, r1.xyzx, r1.xyzx
  sqrt r3.w, r3.w
  lt r3.w, cb2[27].y, r3.w
  if_nz r3.w
    ld_indexable(texture2d)(float,float,float,float) r0.xyz, r0.xyzw, t1.xyzw
    mad r0.xyz, r0.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), l(-1.000000, -1.000000, -1.000000, 0.000000)
    mov r3.xyz, -r3.xyzx
    imm_atomic_alloc r4.x, u0
    mov r2.w, cb2[26].x
    store_structured u0.xyzw, r4.x, l(0), r2.xyzw
    mov r0.w, l(0)
    store_structured u1.xyzw, r4.x, l(0), r0.xyzw
    mov r1.w, l(1.000000)
    store_structured u1.xyzw, r4.x, l(16), r1.xyzw
    mov r3.w, l(0)
    store_structured u1.xyzw, r4.x, l(32), r3.xyzw
  endif 
endif 
ret 
// Approximately 63 instruction slots used
