//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer TexInfo
// {
//
//   float4 f4ColorEffect;              // Offset:    0 Size:    16 [unused]
//   float fBlurStrength;               // Offset:   16 Size:     4 [unused]
//   uint uBlur;                        // Offset:   20 Size:     4 [unused]
//   uint uEnhancedEdges;               // Offset:   24 Size:     4 [unused]
//   uint uMeanFilter;                  // Offset:   28 Size:     4 [unused]
//   float fBloomOriginalIntensity;     // Offset:   32 Size:     4 [unused]
//   float fBloomIntensity;             // Offset:   36 Size:     4 [unused]
//   float fBloomOriginalSaturation;    // Offset:   40 Size:     4 [unused]
//   float fBloomSaturation;            // Offset:   44 Size:     4 [unused]
//   float fRayExposure;                // Offset:   48 Size:     4 [unused]
//   float fRayDecay;                   // Offset:   52 Size:     4 [unused]
//   float fRayDensity;                 // Offset:   56 Size:     4 [unused]
//   float fRayWeight;                  // Offset:   60 Size:     4 [unused]
//   float fTimeDelta;                  // Offset:   64 Size:     4 [unused]
//   float fBloomBlurDistance;          // Offset:   68 Size:     4 [unused]
//   float fDoFFar;                     // Offset:   72 Size:     4
//   float fDoFNear;                    // Offset:   76 Size:     4
//   float2 f2RayLightPos;              // Offset:   80 Size:     8 [unused]
//   float2 f2rcpFrame;                 // Offset:   88 Size:     8 [unused]
//   float4 f4rcpFrameOpt;              // Offset:   96 Size:    16 [unused]
//   float4 f4DoFParams;                // Offset:  112 Size:    16 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// transparentDepthTex               texture   float          2d   22        1
// opaqueDepthTex                    texture   float          2d   23        1
// TexInfo                           cbuffer      NA          NA    7        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_POSITION              0   xyzw        0      POS  float   xy  
// TEXCOORD                 0   xy          1     NONE  float       
// TEXCOORD                 2   xyzw        2     NONE  float       
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_TARGET                0   xyzw        0   TARGET  float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb7[5], immediateIndexed
dcl_resource_texture2d (float,float,float,float) t22
dcl_resource_texture2d (float,float,float,float) t23
dcl_input_ps_siv linear noperspective v0.xy, position
dcl_output o0.xyzw
dcl_temps 2
ftoi r0.xy, v0.xyxx
mov r0.zw, l(0,0,0,0)
ld_indexable(texture2d)(float,float,float,float) r1.x, r0.xyww, t23.xyzw
ld_indexable(texture2d)(float,float,float,float) r0.x, r0.xyzw, t22.xyzw
add r0.x, r0.x, -cb7[4].w
add r0.y, r1.x, -cb7[4].w
div r0.xy, cb7[4].zzzz, r0.xyxx
min r0.x, r0.y, r0.x
add r0.xyz, -r0.xxxx, l(1.000000, 0.997000, 0.999000, 0.000000)
mul_sat r0.yz, r0.yyzy, l(0.000000, 333.333344, 12.658228, 0.000000)
mov o0.x, r0.x
add r0.x, -r0.y, l(1.000000)
add r0.x, r0.z, r0.x
min o0.y, r0.x, l(1.000000)
mov o0.zw, l(0,0,1.000000,1.000000)
ret 
// Approximately 16 instruction slots used
