//
// Generated by Microsoft (R) HLSL Shader Compiler 9.29.952.3111
//
//
// Buffer Definitions: 
//
// cbuffer cbPerFrame
// {
//
//   float4x4 g_mView;                  // Offset:    0 Size:    64 [unused]
//   float4x4 g_mViewInv;               // Offset:   64 Size:    64 [unused]
//   float4x4 g_mProjection;            // Offset:  128 Size:    64 [unused]
//   float4x4 g_mProjectionInv;         // Offset:  192 Size:    64
//   float4x4 g_mProjectionInvViewport; // Offset:  256 Size:    64 [unused]
//   float4 g_f4AmbientColorUp;         // Offset:  320 Size:    16
//   float4 g_f4AmbientColorDown;       // Offset:  336 Size:    16
//   float3 g_f3CameraPos;              // Offset:  352 Size:    12
//   float g_fAlphaTest;                // Offset:  364 Size:     4 [unused]
//   uint g_uNumLights;                 // Offset:  368 Size:     4 [unused]
//   uint g_uNumSpotLights;             // Offset:  372 Size:     4 [unused]
//   uint g_uWindowWidth;               // Offset:  376 Size:     4 [unused]
//   uint g_uWindowHeight;              // Offset:  380 Size:     4 [unused]
//   uint g_uMaxNumLightsPerTile;       // Offset:  384 Size:     4
//   uint g_uMaxNumElementsPerTile;     // Offset:  388 Size:     4
//   uint g_uNumTilesX;                 // Offset:  392 Size:     4
//   uint g_uNumTilesY;                 // Offset:  396 Size:     4 [unused]
//   uint g_uMaxVPLs;                   // Offset:  400 Size:     4 [unused]
//   uint g_uMaxNumVPLsPerTile;         // Offset:  404 Size:     4 [unused]
//   uint g_uMaxNumVPLElementsPerTile;  // Offset:  408 Size:     4 [unused]
//   float g_fVPLSpotStrength;          // Offset:  412 Size:     4 [unused]
//   float g_fVPLSpotRadius;            // Offset:  416 Size:     4 [unused]
//   float g_fVPLPointStrength;         // Offset:  420 Size:     4 [unused]
//   float g_fVPLPointRadius;           // Offset:  424 Size:     4 [unused]
//   float g_fVPLRemoveBackFaceContrib; // Offset:  428 Size:     4 [unused]
//   float g_fVPLColorThreshold;        // Offset:  432 Size:     4 [unused]
//   float g_fVPLBrightnessThreshold;   // Offset:  436 Size:     4 [unused]
//   float g_fPerFramePad1;             // Offset:  440 Size:     4 [unused]
//   float g_fPerFramePad2;             // Offset:  444 Size:     4 [unused]
//
// }
//
// cbuffer TexInfo
// {
//
//   float4 f4ColorAmbient;             // Offset:    0 Size:    16 [unused]
//   float fA;                          // Offset:   16 Size:     4 [unused]
//   float fH;                          // Offset:   20 Size:     4
//   float fBumpStrength;               // Offset:   24 Size:     4
//   float frTransparency;              // Offset:   28 Size:     4 [unused]
//   float4 f4ColorSSS;                 // Offset:   32 Size:    16
//   float4 f4SSSBRDFParams;            // Offset:   48 Size:    16
//   uint uImage;                       // Offset:   64 Size:     4 [unused]
//   uint uGlow;                        // Offset:   68 Size:     4
//   uint uSpecular;                    // Offset:   72 Size:     4
//   uint uBump;                        // Offset:   76 Size:     4
//   uint uImageBlack;                  // Offset:   80 Size:     4 [unused]
//   uint uGlowAsImage;                 // Offset:   84 Size:     4
//   uint uSpecularAsImage;             // Offset:   88 Size:     4 [unused]
//   uint uHeightAsImage;               // Offset:   92 Size:     4 [unused]
//   uint uImageWhite;                  // Offset:   96 Size:     4 [unused]
//   uint uGlowWhite;                   // Offset:  100 Size:     4 [unused]
//   uint uSpecularWhite;               // Offset:  104 Size:     4
//   uint uHeight;                      // Offset:  108 Size:     4 [unused]
//   uint uShadingOn;                   // Offset:  112 Size:     4
//   uint uGlowAsAmbient;               // Offset:  116 Size:     4
//   uint uChromaKeying;                // Offset:  120 Size:     4 [unused]
//   uint uEnvironment;                 // Offset:  124 Size:     4
//   uint uPOM;                         // Offset:  128 Size:     4
//   uint uTexBRDF;                     // Offset:  132 Size:     4 [unused]
//   uint uTexSSS;                      // Offset:  136 Size:     4
//   uint uReflectionMap;               // Offset:  140 Size:     4
//   uint uixPos;                       // Offset:  144 Size:     4
//   uint uiyPos;                       // Offset:  148 Size:     4
//   uint uixPics;                      // Offset:  152 Size:     4
//   uint uiyPics;                      // Offset:  156 Size:     4
//   float fSpecularRoughness;          // Offset:  160 Size:     4
//   float fSpecularIOR;                // Offset:  164 Size:     4
//   uint uPad1;                        // Offset:  168 Size:     4 [unused]
//   uint uPad2;                        // Offset:  172 Size:     4 [unused]
//
// }
//
// cbuffer ViewportArt
// {
//
//   float4 f4ColorViewportOutline;     // Offset:    0 Size:    16
//   float4 f4FogParams;                // Offset:   16 Size:    16
//   float4x4 mColorModification;       // Offset:   32 Size:    64
//   uint uStyleColor;                  // Offset:   96 Size:     4
//   uint uStyleHalfTransparent;        // Offset:  100 Size:     4
//   uint uStylePopart;                 // Offset:  104 Size:     4 [unused]
//   uint uStyleOutlining;              // Offset:  108 Size:     4
//   uint uStyleMonochrome;             // Offset:  112 Size:     4 [unused]
//   uint uStyleOwn;                    // Offset:  116 Size:     4 [unused]
//   uint uStyleFog;                    // Offset:  120 Size:     4
//   uint uPad0;                        // Offset:  124 Size:     4 [unused]
//
// }
//
//
// Resource Bindings:
//
// Name                                 Type  Format         Dim Slot Elements
// ------------------------------ ---------- ------- ----------- ---- --------
// g_Sampler                         sampler      NA          NA    0        1
// g_pointLightCenterAndRadiusBuffer    texture  float4         buf    2        1
// g_pointLightColorBuffer           texture  float4         buf    3        1
// g_perTilePointLightIndexBuffer    texture    uint         buf    4        1
// g_spotLightCenterAndRadiusBuffer    texture  float4         buf    5        1
// g_spotLightColorBuffer            texture  float4         buf    6        1
// g_spotLightSpotParamsBuffer       texture  float4         buf    7        1
// g_perTileSpotLightIndexBuffer     texture    uint         buf    8        1
// tex2D[0]                          texture  float4          2d   15        1
// tex2D[1]                          texture  float4          2d   16        1
// tex2D[3]                          texture  float4          2d   18        1
// tex2D[4]                          texture  float4          2d   19        1
// tex2D[5]                          texture  float4          2d   20        1
// tex2D[6]                          texture  float4          2d   21        1
// cbPerFrame                        cbuffer      NA          NA    2        1
// TexInfo                           cbuffer      NA          NA    5        1
// ViewportArt                       cbuffer      NA          NA    6        1
//
//
//
// Input signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_POSITION              0   xyzw        0      POS  float   xyz 
// NORMAL                   0   xyz         1     NONE  float   xyz 
// TANGENT                  0   xyz         2     NONE  float   xyz 
// BITANGENT                0   xyz         3     NONE  float   xyz 
// TEXCOORD                 0   xy          4     NONE  float   xy  
// TEXCOORD                 1   xyz         5     NONE  float   xyz 
// TEXCOORD                 2   xyzw        6     NONE  float   xyzw
//
//
// Output signature:
//
// Name                 Index   Mask Register SysValue Format   Used
// -------------------- ----- ------ -------- -------- ------ ------
// SV_TARGET                0   xyzw        0   TARGET  float   xyzw
//
ps_5_0
dcl_globalFlags refactoringAllowed
dcl_constantbuffer cb2[25], immediateIndexed
dcl_constantbuffer cb5[11], immediateIndexed
dcl_constantbuffer cb6[8], immediateIndexed
dcl_sampler s0, mode_default
dcl_resource_buffer (float,float,float,float) t2
dcl_resource_buffer (float,float,float,float) t3
dcl_resource_buffer (uint,uint,uint,uint) t4
dcl_resource_buffer (float,float,float,float) t5
dcl_resource_buffer (float,float,float,float) t6
dcl_resource_buffer (float,float,float,float) t7
dcl_resource_buffer (uint,uint,uint,uint) t8
dcl_resource_texture2d (float,float,float,float) t15
dcl_resource_texture2d (float,float,float,float) t16
dcl_resource_texture2d (float,float,float,float) t18
dcl_resource_texture2d (float,float,float,float) t19
dcl_resource_texture2d (float,float,float,float) t20
dcl_resource_texture2d (float,float,float,float) t21
dcl_input_ps_siv linear noperspective v0.xyz, position
dcl_input_ps linear v1.xyz
dcl_input_ps linear v2.xyz
dcl_input_ps linear v3.xyz
dcl_input_ps linear v4.xy
dcl_input_ps linear v5.xyz
dcl_input_ps linear v6.xyzw
dcl_output o0.xyzw
dcl_temps 23
ult r0.xy, l(1, 1, 0, 0), cb5[9].ywyy
or r0.x, r0.y, r0.x
utof r1.xyzw, cb5[9].xyzw
div r0.yz, r1.xxyx, r1.zzwz
div r1.xy, l(1.000000, 1.000000, 1.000000, 1.000000), r1.zwzz
mad r0.yz, v4.xxyx, r1.xxyx, r0.yyzy
movc r0.xy, r0.xxxx, r0.yzyy, v4.xyxx
div r1.xyz, v6.xyzx, v6.wwww
dp3 r0.w, v1.xyzx, v1.xyzx
rsq r0.w, r0.w
mul r2.xyz, r0.wwww, v1.xyzx
mul r3.xyz, r2.yzxy, l(0.000000, 0.000000, 1.000000, 0.000000)
mad r4.xyz, r2.yzxy, l(1.000000, 0.000000, 0.000000, 0.000000), -r3.yzxy
mad r3.xyz, -r2.zxyz, l(1.000000, 0.000000, 0.000000, 0.000000), r3.xyzx
dp2 r0.w, r4.xyxx, r4.xyxx
sqrt r1.w, r0.w
dp2 r2.w, r3.xzxx, r3.xzxx
sqrt r3.w, r2.w
lt r1.w, r3.w, r1.w
if_nz r1.w
  rsq r0.w, r0.w
  mul r4.xyz, r0.wwww, r4.xyzx
else 
  rsq r0.w, r2.w
  mul r4.xyz, r0.wwww, r3.xyzx
endif 
mul r3.xyz, r2.zxyz, r4.yzxy
mad r3.xyz, r2.yzxy, r4.zxyz, -r3.xyzx
dp3 r0.w, -r3.xyzx, -r3.xyzx
rsq r0.w, r0.w
mul r3.xyz, r0.wwww, -r3.xyzx
ieq r5.xy, cb5[8].xxxx, l(1, 2, 0, 0)
if_nz r5.x
  add r5.xzw, v5.xxyz, -v6.xxyz
  dp3 r0.w, r5.xzwx, r5.xzwx
  rsq r0.w, r0.w
  mul r5.xzw, r0.wwww, r5.xxzw
  dp3 r6.x, -r5.xzwx, r4.xyzx
  dp3 r6.y, -r5.xzwx, r3.xyzx
  dp3 r0.w, -r5.xzwx, r2.xyzx
  mul r5.xz, r6.xxyx, l(-0.020000, 0.000000, -0.020000, 0.000000)
  div r5.xz, r5.xxzx, r0.wwww
  mad r0.w, r0.w, l(-15.000000), l(20.000000)
  ftoi r1.w, r0.w
  round_z r0.w, r0.w
  div r0.w, l(1.000000, 1.000000, 1.000000, 1.000000), r0.w
  mul r6.xy, r0.wwww, r5.xzxx
  deriv_rtx_coarse r6.zw, r0.xxxy
  deriv_rty_coarse r7.xy, r0.xyxx
  add r2.w, -r0.w, l(1.000000)
  iadd r8.x, r1.w, l(1)
  mov r7.zw, l(0,0,0,0)
  mov r9.xyzw, l(0,0,0,0)
  mov r10.y, r2.w
  mov r10.xzw, l(0,0,1.000000,0)
  loop 
    ige r1.w, r10.x, r8.x
    breakc_nz r1.w
    add r11.xy, r0.xyxx, r7.zwzz
    sample_d_indexable(texture2d)(float,float,float,float) r1.w, r11.xyxx, t20.yzwx, s0, r6.zwzz, r7.xyxx
    add r1.w, r1.w, r10.w
    mul r11.w, r1.w, l(0.500000)
    lt r3.w, r10.y, r11.w
    add r4.w, -r10.z, r10.w
    mad r1.w, -r1.w, l(0.500000), r10.w
    add r1.w, r10.y, r1.w
    add r1.w, -r10.z, r1.w
    div r1.w, r4.w, r1.w
    mad r12.xy, r1.wwww, r6.xyxx, r9.xyxx
    iadd r11.x, r10.x, l(1)
    mad r12.zw, r5.xxxz, r0.wwww, r7.zzzw
    add r11.y, -r0.w, r10.y
    movc r12.zw, r3.wwww, r7.zzzw, r12.zzzw
    movc r9.xy, r3.wwww, r9.xyxx, r7.zwzz
    movc r9.zw, r3.wwww, r12.xxxy, r9.zzzw
    mov r8.yzw, r10.yyzw
    mov r11.z, r8.y
    movc r10.xyzw, r3.wwww, r8.xyzw, r11.xyzw
    mov r7.zw, r12.zzzw
  endloop 
  add r0.xy, r0.xyxx, r9.zwzz
  sample_indexable(texture2d)(float,float,float,float) r0.w, r0.xyxx, t20.xzwy, s0
  mul r5.xzw, r3.xxyz, r0.wwww
  mad r5.xzw, r0.wwww, r4.xxyz, r5.xxzw
  add r5.xzw, r5.xxzw, v1.xxyz
  dp3 r0.w, r5.xzwx, r5.xzwx
  rsq r0.w, r0.w
  mul r5.xzw, r0.wwww, r5.xxzw
else 
  mov r5.xzw, v1.xxyz
endif 
if_nz r5.y
  add r6.xyz, v5.xyzx, -v6.xyzx
  dp3 r0.w, r6.xyzx, r6.xyzx
  rsq r0.w, r0.w
  mul r6.xyz, r0.wwww, r6.xyzx
  dp3 r7.x, r6.xyzx, r4.xyzx
  dp3 r7.y, r6.xyzx, v3.xyzx
  dp3 r7.z, r6.xyzx, r2.xyzx
  dp3 r0.w, r7.xyzx, r7.xyzx
  rsq r0.w, r0.w
  mul r2.xyz, r0.wwww, r7.xyzx
  div r2.xyz, r2.xyzx, r2.zzzz
  sample_indexable(texture2d)(float,float,float,float) r6.xy, r0.xyxx, t20.wzxy, s0
  mov_sat r6.x, r6.x
  mul r0.w, r6.x, r6.y
  add r1.w, r6.y, l(1.000000)
  div r0.w, r0.w, r1.w
  mul r0.w, r0.w, l(0.010000)
  mov r0.z, l(0)
  mad r6.xyz, r2.xyzx, r0.wwww, r0.xyzx
  sample_indexable(texture2d)(float,float,float,float) r7.xy, r6.xyxx, t20.zwxy, s0
  add_sat r0.w, -r6.z, r7.y
  mul r0.w, r0.w, r7.x
  add r1.w, r7.x, l(1.000000)
  div r0.w, r0.w, r1.w
  mul r0.w, r0.w, l(0.010000)
  mad r6.xyz, r2.xyzx, r0.wwww, r6.xyzx
  sample_indexable(texture2d)(float,float,float,float) r7.xy, r6.xyxx, t20.zwxy, s0
  add_sat r0.w, -r6.z, r7.y
  mul r0.w, r0.w, r7.x
  add r1.w, r7.x, l(1.000000)
  div r0.w, r0.w, r1.w
  mul r0.w, r0.w, l(0.010000)
  mad r6.xyz, r2.xyzx, r0.wwww, r6.xyzx
  sample_indexable(texture2d)(float,float,float,float) r7.xy, r6.xyxx, t20.zwxy, s0
  add_sat r0.w, -r6.z, r7.y
  mul r0.w, r0.w, r7.x
  add r1.w, r7.x, l(1.000000)
  div r0.w, r0.w, r1.w
  mul r0.w, r0.w, l(0.010000)
  mad r6.xyz, r2.xyzx, r0.wwww, r6.xyzx
  sample_indexable(texture2d)(float,float,float,float) r7.xy, r6.xyxx, t20.zwxy, s0
  add_sat r0.w, -r6.z, r7.y
  mul r0.w, r0.w, r7.x
  add r1.w, r7.x, l(1.000000)
  div r0.w, r0.w, r1.w
  mul r0.w, r0.w, l(0.010000)
  mad r6.xyz, r2.xyzx, r0.wwww, r6.xyzx
  sample_indexable(texture2d)(float,float,float,float) r7.xy, r6.xyxx, t20.zwxy, s0
  add_sat r0.w, -r6.z, r7.y
  mul r0.w, r0.w, r7.x
  add r1.w, r7.x, l(1.000000)
  div r0.w, r0.w, r1.w
  mul r0.w, r0.w, l(0.010000)
  mad r6.xyz, r2.xyzx, r0.wwww, r6.xyzx
  sample_indexable(texture2d)(float,float,float,float) r7.xy, r6.xyxx, t20.zwxy, s0
  add_sat r0.w, -r6.z, r7.y
  mul r0.w, r0.w, r7.x
  add r1.w, r7.x, l(1.000000)
  div r0.w, r0.w, r1.w
  mul r0.w, r0.w, l(0.010000)
  mad r6.xyz, r2.xyzx, r0.wwww, r6.xyzx
  sample_indexable(texture2d)(float,float,float,float) r7.xy, r6.xyxx, t20.zwxy, s0
  add_sat r0.w, -r6.z, r7.y
  mul r0.w, r0.w, r7.x
  add r1.w, r7.x, l(1.000000)
  div r0.w, r0.w, r1.w
  mul r0.w, r0.w, l(0.010000)
  mad r6.xyz, r2.xyzx, r0.wwww, r6.xyzx
  sample_indexable(texture2d)(float,float,float,float) r7.xy, r6.xyxx, t20.zwxy, s0
  add_sat r0.w, -r6.z, r7.y
  mul r0.w, r0.w, r7.x
  add r1.w, r7.x, l(1.000000)
  div r0.w, r0.w, r1.w
  mul r0.w, r0.w, l(0.010000)
  mad r6.xyz, r2.xyzx, r0.wwww, r6.xyzx
  sample_indexable(texture2d)(float,float,float,float) r7.xy, r6.xyxx, t20.zwxy, s0
  add_sat r0.w, -r6.z, r7.y
  mul r0.w, r0.w, r7.x
  add r1.w, r7.x, l(1.000000)
  div r0.w, r0.w, r1.w
  mul r0.w, r0.w, l(0.010000)
  mad r6.xyz, r2.xyzx, r0.wwww, r6.xyzx
  sample_indexable(texture2d)(float,float,float,float) r7.xy, r6.xyxx, t20.zwxy, s0
  add_sat r0.w, -r6.z, r7.y
  mul r0.w, r0.w, r7.x
  add r1.w, r7.x, l(1.000000)
  div r0.w, r0.w, r1.w
  mul r0.w, r0.w, l(0.010000)
  mad r6.xyz, r2.xyzx, r0.wwww, r6.xyzx
  sample_indexable(texture2d)(float,float,float,float) r7.xy, r6.xyxx, t20.zwxy, s0
  add_sat r0.w, -r6.z, r7.y
  mul r0.w, r0.w, r7.x
  add r1.w, r7.x, l(1.000000)
  div r0.w, r0.w, r1.w
  mul r0.w, r0.w, l(0.010000)
  mad r6.xyz, r2.xyzx, r0.wwww, r6.xyzx
  sample_indexable(texture2d)(float,float,float,float) r7.xy, r6.xyxx, t20.zwxy, s0
  add_sat r0.w, -r6.z, r7.y
  mul r0.w, r0.w, r7.x
  add r1.w, r7.x, l(1.000000)
  div r0.w, r0.w, r1.w
  mul r0.w, r0.w, l(0.010000)
  mad r6.xyz, r2.xyzx, r0.wwww, r6.xyzx
  sample_indexable(texture2d)(float,float,float,float) r7.xy, r6.xyxx, t20.zwxy, s0
  add_sat r0.w, -r6.z, r7.y
  mul r0.w, r0.w, r7.x
  add r1.w, r7.x, l(1.000000)
  div r0.w, r0.w, r1.w
  mul r0.w, r0.w, l(0.010000)
  mad r6.xyz, r2.xyzx, r0.wwww, r6.xyzx
  sample_indexable(texture2d)(float,float,float,float) r6.xy, r6.xyxx, t20.zwxy, s0
  add_sat r0.w, -r6.z, r6.y
  mul r0.w, r0.w, r6.x
  add r1.w, r6.x, l(1.000000)
  div r0.w, r0.w, r1.w
  mul r0.w, r2.z, r0.w
  mad r0.w, r0.w, l(0.010000), r6.z
  mul r2.xyz, r2.xyzx, r0.wwww
  mad r6.xyz, r2.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r0.xyzx
  sample_indexable(texture2d)(float,float,float,float) r0.z, r6.xyxx, t20.xywz, s0
  lt r0.z, r6.z, r0.z
  if_nz r0.z
    mad r7.xyz, r2.xyzx, l(0.250000, 0.250000, 0.250000, 0.000000), r6.xyzx
  else 
    mad r7.xyz, -r2.xyzx, l(0.250000, 0.250000, 0.250000, 0.000000), r6.xyzx
  endif 
  sample_indexable(texture2d)(float,float,float,float) r0.z, r7.xyxx, t20.xywz, s0
  lt r0.z, r7.z, r0.z
  if_nz r0.z
    mad r6.xyz, r2.xyzx, l(0.125000, 0.125000, 0.125000, 0.000000), r7.xyzx
  else 
    mad r6.xyz, -r2.xyzx, l(0.125000, 0.125000, 0.125000, 0.000000), r7.xyzx
  endif 
  sample_indexable(texture2d)(float,float,float,float) r0.z, r6.xyxx, t20.xywz, s0
  lt r0.z, r6.z, r0.z
  if_nz r0.z
    mad r7.xyz, r2.xyzx, l(0.062500, 0.062500, 0.062500, 0.000000), r6.xyzx
  else 
    mad r7.xyz, -r2.xyzx, l(0.062500, 0.062500, 0.062500, 0.000000), r6.xyzx
  endif 
  sample_indexable(texture2d)(float,float,float,float) r0.z, r7.xyxx, t20.xywz, s0
  lt r0.z, r7.z, r0.z
  if_nz r0.z
    mad r6.xyz, r2.xyzx, l(0.031250, 0.031250, 0.031250, 0.000000), r7.xyzx
  else 
    mad r6.xyz, -r2.xyzx, l(0.031250, 0.031250, 0.031250, 0.000000), r7.xyzx
  endif 
  sample_indexable(texture2d)(float,float,float,float) r0.z, r6.xyxx, t20.xywz, s0
  lt r0.z, r6.z, r0.z
  if_nz r0.z
    mad r7.xyz, r2.xyzx, l(0.015625, 0.015625, 0.015625, 0.000000), r6.xyzx
  else 
    mad r7.xyz, -r2.xyzx, l(0.015625, 0.015625, 0.015625, 0.000000), r6.xyzx
  endif 
  sample_indexable(texture2d)(float,float,float,float) r0.z, r7.xyxx, t20.xywz, s0
  lt r0.z, r7.z, r0.z
  if_nz r0.z
    mad r0.xy, r2.xyxx, l(0.007813, 0.007813, 0.000000, 0.000000), r7.xyxx
  else 
    mad r0.xy, -r2.xyxx, l(0.007813, 0.007813, 0.000000, 0.000000), r7.xyxx
  endif 
  sample_indexable(texture2d)(float,float,float,float) r0.z, r0.xyxx, t20.xywz, s0
  mul r2.xyz, r3.xyzx, r0.zzzz
  mad r2.xyz, r0.zzzz, r4.xyzx, r2.xyzx
  add r2.xyz, r2.xyzx, r5.xzwx
  dp3 r0.z, r2.xyzx, r2.xyzx
  rsq r0.z, r0.z
  mul r5.xzw, r0.zzzz, r2.xxyz
endif 
sample_indexable(texture2d)(float,float,float,float) r2.xyzw, r0.xyxx, t15.xyzw, s0
if_nz cb5[4].w
  sample_indexable(texture2d)(float,float,float,float) r0.zw, r0.xyxx, t18.zwxy, s0
  mad r0.zw, r0.zzzw, l(0.000000, 0.000000, 2.000000, 2.000000), l(0.000000, 0.000000, -1.000000, -1.000000)
  mul r0.zw, r0.zzzw, cb5[1].zzzz
  mul r3.xyz, -r0.wwww, v3.xyzx
  mad r3.xyz, r0.zzzz, v2.xyzx, r3.xyzx
  add r3.xyz, r3.xyzx, r5.xzwx
  dp3 r0.z, r3.xyzx, r3.xyzx
  rsq r0.z, r0.z
  mul r5.xzw, r0.zzzz, r3.xxyz
endif 
add r3.xyz, -r1.xyzx, cb2[22].xyzx
dp3 r0.z, r3.xyzx, r3.xyzx
rsq r0.z, r0.z
mul r4.xyz, r0.zzzz, r3.xyzx
if_nz cb5[4].z
  mov r6.xyz, r2.xyzx
else 
  mov r6.xyz, l(0,0,0,0)
endif 
mad r0.w, r5.z, l(0.500000), l(0.500000)
add r1.w, -r0.w, l(1.000000)
mul r7.xyz, r1.wwww, cb2[21].xyzx
mad r7.xyz, cb2[20].xyzx, r0.wwww, r7.xyzx
mul r8.xy, v0.xyxx, l(0.031250, 0.031250, 0.000000, 0.000000)
round_ni r8.xy, r8.xyxx
utof r0.w, cb2[24].z
mad r0.w, r8.y, r0.w, r8.x
ftou r0.w, r0.w
imul null, r1.w, cb2[24].y, r0.w
ld_indexable(buffer)(uint,uint,uint,uint) r3.w, r1.wwww, t4.yzwx
imad r8.xyzw, cb2[24].yyyy, r0.wwww, l(1, 4, 2, 3)
ld_indexable(buffer)(uint,uint,uint,uint) r0.w, r8.xxxx, t4.yzwx
ishl r3.w, r3.w, l(16)
or r0.w, r0.w, r3.w
mad r3.w, v0.z, cb2[15].z, cb2[15].w
div r3.w, l(1.000000, 1.000000, 1.000000, 1.000000), r3.w
lt r0.w, r3.w, r0.w
iadd r4.w, r8.y, cb2[24].x
movc r5.y, r0.w, r8.y, r4.w
ld_indexable(buffer)(uint,uint,uint,uint) r6.w, r8.zzzz, t4.yzwx
ld_indexable(buffer)(uint,uint,uint,uint) r7.w, r8.wwww, t4.yzwx
movc r0.w, r0.w, r6.w, r7.w
iadd r0.w, r5.y, r0.w
dp3 r6.w, r5.xzwx, r5.xzwx
rsq r6.w, r6.w
mul r9.xyz, r5.xzwx, r6.wwww
mul r6.w, cb5[10].x, cb5[10].x
dp3_sat r7.w, r9.xyzx, r4.xyzx
mul r9.w, r6.w, r6.w
mad r10.x, r6.w, r6.w, l(-1.000000)
add r10.y, l(1.000000), -cb5[10].y
mul r10.z, r6.w, l(0.500000)
mad r6.w, -r6.w, l(0.500000), l(1.000000)
mad r7.w, r7.w, r6.w, r10.z
div r7.w, l(1.000000, 1.000000, 1.000000, 1.000000), r7.w
sample_indexable(texture2d)(float,float,float,float) r11.xyz, r0.xyxx, t21.xyzw, s0
add r12.xyz, r2.xyzx, r2.xyzx
dp3 r10.w, r11.xyzx, r11.xyzx
sqrt r10.w, r10.w
add r11.xyz, v5.xyzx, -v6.xyzx
dp3 r11.w, r11.xyzx, r11.xyzx
rsq r12.w, r11.w
mul r13.xyz, r11.xyzx, r12.wwww
dp3 r13.w, -r13.xyzx, r5.xzwx
mad r14.x, r13.w, l(0.500000), l(0.500000)
dp3 r14.y, -r5.xzwx, -r13.xyzx
max r14.y, r14.y, l(0.000000)
dp3 r14.z, -r13.xyzx, -r13.xyzx
mad r14.z, r14.z, l(0.500000), l(0.500000)
mul r14.z, r14.z, cb5[3].x
mad r14.y, cb5[3].x, r14.y, r14.z
dp3 r13.z, r5.xzwx, r13.xyzx
max r14.z, r13.z, l(0.000000)
add r14.w, -r14.z, l(1.000000)
mul r14.w, r14.w, r14.w
max r13.w, r13.w, l(0.000000)
mad r11.xyz, -r11.xyzx, r12.wwww, r5.xzwx
dp3 r12.w, r11.xyzx, r11.xyzx
rsq r12.w, r12.w
mul r11.xyz, r11.xyzx, r12.wwww
dp3_sat r11.x, r5.xzwx, r11.xyzx
lt r11.y, r14.z, l(0.800000)
lt r11.z, l(2.000000), cb5[3].x
and r11.y, r11.z, r11.y
mov r15.w, l(1.000000)
mov r16.xyz, l(0,0,0,0)
mov r17.xyz, l(0,0,0,0)
mov r11.z, r5.y
loop 
  uge r12.w, r11.z, r0.w
  breakc_nz r12.w
  ld_indexable(buffer)(uint,uint,uint,uint) r12.w, r11.zzzz, t4.yzwx
  ld_indexable(buffer)(float,float,float,float) r18.xyzw, r12.wwww, t2.xyzw
  add r19.xyz, -r1.xyzx, r18.xyzx
  dp3 r16.w, r19.xyzx, r19.xyzx
  sqrt r17.w, r16.w
  lt r19.w, r17.w, r18.w
  if_nz r19.w
    rsq r19.w, r16.w
    mul r20.xyz, r19.wwww, r19.xyzx
    div r17.w, r17.w, r18.w
    mul r17.w, r17.w, r17.w
    mad r17.w, -r17.w, r17.w, l(1.000000)
    mul r17.w, r17.w, r17.w
    min r17.w, r17.w, l(1.000000)
    mul r17.w, r17.w, r18.w
    add r16.w, r16.w, l(1.000000)
    div r16.w, r17.w, r16.w
    ld_indexable(buffer)(float,float,float,float) r21.xyz, r12.wwww, t3.xyzw
    dp3_sat r17.w, r20.xyzx, r5.xzwx
    mul r20.xyz, r17.wwww, r21.xyzx
    mul r20.xyz, r16.wwww, r20.xyzx
    mul r20.xyz, r20.xyzx, cb5[1].yyyy
    mad r22.xyz, r3.xyzx, r0.zzzz, r19.xyzx
    dp3 r17.w, r22.xyzx, r22.xyzx
    rsq r17.w, r17.w
    mul r22.xyz, r17.wwww, r22.xyzx
    dp3_sat r17.w, r9.xyzx, r19.xyzx
    dp3_sat r18.w, r9.xyzx, r22.xyzx
    dp3_sat r19.x, r19.xyzx, r22.xyzx
    mul r18.w, r18.w, r18.w
    mad r18.w, r18.w, r10.x, l(1.000000)
    mul r18.w, r18.w, r18.w
    mul r18.w, r18.w, l(3.141590)
    div r18.w, r9.w, r18.w
    add r19.x, -r19.x, l(1.000000)
    mul r19.y, r19.x, r19.x
    mul r19.y, r19.y, r19.y
    mul r19.x, r19.y, r19.x
    mad r19.x, r10.y, r19.x, cb5[10].y
    mad r19.y, r17.w, r6.w, r10.z
    div r19.y, l(1.000000, 1.000000, 1.000000, 1.000000), r19.y
    mul r19.y, r7.w, r19.y
    mul r17.w, r17.w, r18.w
    mul r17.w, r19.x, r17.w
    mul r17.w, r19.y, r17.w
    mul r19.xyz, r17.wwww, r21.xyzx
    mul r19.xyz, r16.wwww, r19.xyzx
    if_nz cb5[6].z
      mul r21.xyz, r20.xyzx, r19.xyzx
      add r21.xyz, r21.xyzx, r21.xyzx
    else 
      mul r19.xyz, r20.xyzx, r19.xyzx
      mul r21.xyz, r12.xyzx, r19.xyzx
    endif 
    mul r19.xyz, r20.xyzx, l(16.000000, 16.000000, 16.000000, 0.000000)
    mul r20.xyz, r21.xyzx, l(16.000000, 16.000000, 16.000000, 0.000000)
  else 
    mov r19.xyz, l(0,0,0,0)
    mov r20.xyz, l(0,0,0,0)
  endif 
  if_nz cb5[8].z
    mov r15.xyz, r18.xyzx
    add r18.xyzw, r15.xyzw, -v6.xyzw
    dp4 r15.x, r18.xyzw, r18.xyzw
    sqrt r15.x, r15.x
    div r15.x, l(1.000000, 1.000000, 1.000000, 1.000000), r15.x
    mul r15.x, r15.x, l(10.000000)
    mul r15.y, r14.y, r15.x
    mul r18.xyz, r15.yyyy, cb5[2].xyzx
    mul r18.xyz, r10.wwww, r18.xyzx
    if_nz r11.y
      mul r21.xyz, r18.xyzx, l(0.066667, 0.066667, 0.066667, 0.000000)
      mul r19.xyz, r19.xyzx, r21.xyzx
      mul r20.xyz, r20.xyzx, r21.xyzx
    else 
      ld_indexable(buffer)(float,float,float,float) r21.xyz, r12.wwww, t3.xyzw
      mul r12.w, r14.x, r15.x
      mul r22.xyz, r13.wwww, r20.xyzx
      mul r22.xyz, r14.wwww, r22.xyzx
      mad r18.xyz, r12.wwww, r2.xyzx, r18.xyzx
      mul r22.xyz, r22.xyzx, cb5[3].zzzz
      mad r18.xyz, r22.xyzx, r15.xxxx, r18.xyzx
      mul r12.w, r11.x, r15.x
      mul r15.xyz, r20.xyzx, r12.wwww
      mad r15.xyz, r15.xyzx, l(0.050000, 0.050000, 0.050000, 0.000000), r18.xyzx
      mul r15.xyz, r21.xyzx, r15.xyzx
      mul r19.xyz, r15.xyzx, r19.xyzx
      mul r20.xyz, r15.xyzx, r20.xyzx
    endif 
  endif 
  add r16.xyz, r16.xyzx, r19.xyzx
  add r17.xyz, r17.xyzx, r20.xyzx
  iadd r11.z, r11.z, l(1)
endloop 
ld_indexable(buffer)(uint,uint,uint,uint) r0.w, r1.wwww, t8.yzwx
ld_indexable(buffer)(uint,uint,uint,uint) r1.w, r8.xxxx, t8.yzwx
ishl r0.w, r0.w, l(16)
or r0.w, r1.w, r0.w
lt r0.w, r3.w, r0.w
movc r1.w, r0.w, r8.y, r4.w
ld_indexable(buffer)(uint,uint,uint,uint) r3.w, r8.zzzz, t8.yzwx
ld_indexable(buffer)(uint,uint,uint,uint) r4.w, r8.wwww, t8.yzwx
movc r0.w, r0.w, r3.w, r4.w
iadd r0.w, r1.w, r0.w
dp3_sat r3.w, r9.xyzx, -r4.xyzx
mad r3.w, r3.w, r6.w, r10.z
div r3.w, l(1.000000, 1.000000, 1.000000, 1.000000), r3.w
add r4.xyz, r6.xyzx, r6.xyzx
mov r8.w, l(1.000000)
mov r6.xyz, r16.xyzx
mov r12.xyz, r17.xyzx
mov r4.w, r1.w
loop 
  uge r5.y, r4.w, r0.w
  breakc_nz r5.y
  ld_indexable(buffer)(uint,uint,uint,uint) r5.y, r4.wwww, t8.yxzw
  ld_indexable(buffer)(float,float,float,float) r15.xyzw, r5.yyyy, t5.xyzw
  ld_indexable(buffer)(float,float,float,float) r18.xyzw, r5.yyyy, t7.xyzw
  mad r7.w, -r18.x, r18.x, l(1.000000)
  mad r7.w, -r18.y, r18.y, r7.w
  sqrt r7.w, r7.w
  lt r11.z, l(0.000000), r18.z
  movc r19.z, r11.z, r7.w, -r7.w
  mov r19.xy, r18.xyxx
  mad r20.xyz, -r15.wwww, r19.xyzx, r15.xyzx
  add r20.xyz, -r1.xyzx, r20.xyzx
  dp3 r7.w, r20.xyzx, r20.xyzx
  rsq r12.w, r7.w
  mul r21.xyz, r12.wwww, r20.xyzx
  sqrt r12.w, r7.w
  dp3 r15.w, -r21.xyzx, r19.xyzx
  movc r11.z, r11.z, r18.z, -r18.z
  lt r16.w, r12.w, r18.w
  lt r17.w, r11.z, r15.w
  and r16.w, r16.w, r17.w
  if_nz r16.w
    add r11.z, -r11.z, r15.w
    add r15.w, -r15.w, l(1.000000)
    div r11.z, r11.z, r15.w
    mul r11.z, r11.z, r11.z
    min r11.z, r11.z, l(1.000000)
    div r12.w, r12.w, r18.w
    mul r12.w, r12.w, r12.w
    mad r12.w, -r12.w, r12.w, l(1.000000)
    mul r12.w, r12.w, r12.w
    min r12.w, r12.w, l(1.000000)
    mul r12.w, r12.w, r18.w
    add r7.w, r7.w, l(1.000000)
    div r7.w, r12.w, r7.w
    ld_indexable(buffer)(float,float,float,float) r18.xyz, r5.yyyy, t6.xyzw
    dp3_sat r12.w, r21.xyzx, r5.xzwx
    mul r19.xyz, r12.wwww, r18.xyzx
    mul r19.xyz, r7.wwww, r19.xyzx
    mul r19.xyz, r11.zzzz, r19.xyzx
    mul r19.xyz, r19.xyzx, cb5[1].yyyy
    mad r21.xyz, -r3.xyzx, r0.zzzz, r20.xyzx
    dp3 r12.w, r21.xyzx, r21.xyzx
    rsq r12.w, r12.w
    mul r21.xyz, r12.wwww, r21.xyzx
    dp3_sat r12.w, r9.xyzx, r20.xyzx
    dp3_sat r15.w, r9.xyzx, r21.xyzx
    dp3_sat r16.w, r20.xyzx, r21.xyzx
    mul r15.w, r15.w, r15.w
    mad r15.w, r15.w, r10.x, l(1.000000)
    mul r15.w, r15.w, r15.w
    mul r15.w, r15.w, l(3.141590)
    div r15.w, r9.w, r15.w
    add r16.w, -r16.w, l(1.000000)
    mul r17.w, r16.w, r16.w
    mul r17.w, r17.w, r17.w
    mul r16.w, r16.w, r17.w
    mad r16.w, r10.y, r16.w, cb5[10].y
    mad r17.w, r12.w, r6.w, r10.z
    div r17.w, l(1.000000, 1.000000, 1.000000, 1.000000), r17.w
    mul r17.w, r3.w, r17.w
    mul r12.w, r12.w, r15.w
    mul r12.w, r16.w, r12.w
    mul r12.w, r17.w, r12.w
    mul r18.xyz, r12.wwww, r18.xyzx
    mul r18.xyz, r7.wwww, r18.xyzx
    mul r18.xyz, r11.zzzz, r18.xyzx
    if_nz cb5[6].z
      mul r20.xyz, r19.xyzx, r18.xyzx
      add r20.xyz, r20.xyzx, r20.xyzx
    else 
      mul r18.xyz, r19.xyzx, r18.xyzx
      mul r20.xyz, r4.xyzx, r18.xyzx
    endif 
    mul r18.xyz, r19.xyzx, l(16.000000, 16.000000, 16.000000, 0.000000)
    mul r19.xyz, r20.xyzx, l(16.000000, 16.000000, 16.000000, 0.000000)
  else 
    mov r18.xyz, l(0,0,0,0)
    mov r19.xyz, l(0,0,0,0)
  endif 
  if_nz cb5[8].z
    mov r8.xyz, r15.xyzx
    add r15.xyzw, r8.xyzw, -v6.xyzw
    dp4 r7.w, r15.xyzw, r15.xyzw
    sqrt r7.w, r7.w
    div r7.w, l(1.000000, 1.000000, 1.000000, 1.000000), r7.w
    mul r7.w, r7.w, l(10.000000)
    mul r8.x, r7.w, r14.y
    mul r8.xyz, r8.xxxx, cb5[2].xyzx
    mul r8.xyz, r10.wwww, r8.xyzx
    if_nz r11.y
      mul r15.xyz, r8.xyzx, l(0.066667, 0.066667, 0.066667, 0.000000)
      mul r18.xyz, r15.xyzx, r18.xyzx
      mul r19.xyz, r15.xyzx, r19.xyzx
    else 
      ld_indexable(buffer)(float,float,float,float) r15.xyz, r5.yyyy, t6.xyzw
      mul r5.y, r7.w, r14.x
      mul r20.xyz, r13.wwww, r19.xyzx
      mul r20.xyz, r14.wwww, r20.xyzx
      mad r8.xyz, r5.yyyy, r2.xyzx, r8.xyzx
      mul r20.xyz, r20.xyzx, cb5[3].zzzz
      mad r8.xyz, r20.xyzx, r7.wwww, r8.xyzx
      mul r5.y, r7.w, r11.x
      mul r20.xyz, r19.xyzx, r5.yyyy
      mad r8.xyz, r20.xyzx, l(0.050000, 0.050000, 0.050000, 0.000000), r8.xyzx
      mul r8.xyz, r15.xyzx, r8.xyzx
      mul r18.xyz, r8.xyzx, r18.xyzx
      mul r19.xyz, r8.xyzx, r19.xyzx
    endif 
  endif 
  add r6.xyz, r6.xyzx, r18.xyzx
  add r12.xyz, r12.xyzx, r19.xyzx
  iadd r4.w, r4.w, l(1)
endloop 
mul r1.xyz, r2.wwww, r12.xyzx
if_nz cb5[4].y
  if_nz cb5[7].y
    mov r3.xyz, r7.xyzx
  else 
    if_nz cb5[5].y
      add_sat r4.xyz, -r7.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
      mul r3.xyz, r2.xyzx, r4.xyzx
    else 
      sample_indexable(texture2d)(float,float,float,float) r4.xyz, r0.xyxx, t16.xyzw, s0
      add_sat r8.xyz, -r7.xyzx, l(1.000000, 1.000000, 1.000000, 0.000000)
      mul r3.xyz, r4.xyzx, r8.xyzx
    endif 
  endif 
else 
  mov r3.xyz, l(0,0,0,0)
endif 
mul r3.xyz, r3.xyzx, l(0.750000, 0.750000, 0.750000, 0.000000)
mad r3.xyz, r6.xyzx, l(0.500000, 0.500000, 0.500000, 0.000000), r3.xyzx
add r3.xyz, r7.xyzx, r3.xyzx
mad r1.xyz, r1.xyzx, l(2.000000, 2.000000, 2.000000, 0.000000), r3.xyzx
mul r1.xyz, r1.xyzx, r2.xyzx
movc r1.xyz, cb5[7].xxxx, r1.xyzx, r2.xyzx
mov r1.w, l(1.000000)
if_nz cb5[7].w
  add r0.z, r13.z, r13.z
  mad r0.zw, r5.xxxz, -r0.zzzz, r13.xxxy
  mad r2.x, -r13.z, r13.z, l(1.000000)
  mad r2.x, -r2.x, l(0.980100), l(1.000000)
  sqrt r2.y, r2.x
  mad r2.y, r13.z, l(0.990000), r2.y
  ge r2.x, r2.x, l(0.000000)
  mul r2.yz, r5.xxzx, r2.yyyy
  mad r2.yz, r13.xxyx, l(0.000000, 0.990000, 0.990000, 0.000000), -r2.yyzy
  and r2.xy, r2.yzyy, r2.xxxx
  sample_indexable(texture2d)(float,float,float,float) r2.xyzw, r2.xyxx, t19.xyzw, s0
  sample_indexable(texture2d)(float,float,float,float) r3.xyzw, r0.zwzz, t19.xyzw, s0
  if_nz cb5[8].w
    sample_indexable(texture2d)(float,float,float,float) r0.x, r0.xyxx, t19.wxyz, s0
    add r4.xyzw, -r2.xyzw, r3.xyzw
    mad r4.xyzw, r4.xyzw, l(0.500000, 0.500000, 0.500000, 0.500000), r2.xyzw
    div r4.xyzw, r4.xyzw, cb5[2].wwww
    mul r0.xyzw, r0.xxxx, r4.xyzw
    dp3 r4.x, r1.xyzx, r1.xyzx
    mad r1.xyzw, r0.xyzw, r4.xxxx, r1.xyzw
  else 
    add r0.xyzw, -r2.xyzw, r3.xyzw
    mad r0.xyzw, r0.xyzw, l(0.500000, 0.500000, 0.500000, 0.500000), r2.xyzw
    div r0.xyzw, r0.xyzw, cb5[2].wwww
    dp3 r2.x, r1.xyzx, r1.xyzx
    mad r1.xyzw, r0.xyzw, r2.xxxx, r1.xyzw
  endif 
endif 
mul r0.xyzw, r1.xyzw, l(0.500000, 0.500000, 0.500000, 0.500000)
movc r0.xyzw, cb6[6].yyyy, r0.xyzw, r1.xyzw
lt r1.x, r14.z, cb6[0].w
movc r1.xyz, r1.xxxx, cb6[0].xyzx, r0.xyzx
movc r1.xyz, cb6[6].wwww, r1.xyzx, r0.xyzx
sqrt r1.w, r11.w
div r1.w, r1.w, cb6[1].w
add r2.xyz, r1.wwww, r1.xyzx
movc r0.xyz, cb6[7].zzzz, r2.xyzx, r1.xyzx
dp4 r1.x, r0.xyzw, cb6[2].xyzw
dp4 r1.y, r0.xyzw, cb6[3].xyzw
dp4 r1.z, r0.xyzw, cb6[4].xyzw
dp4 r1.w, r0.xyzw, cb6[5].xyzw
movc o0.xyzw, cb6[6].xxxx, r1.xyzw, r0.xyzw
ret 
// Approximately 650 instruction slots used
